go_binary(
    name = "grafana-import-dashboard",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//common/go/flags",
        "//common/go/logging",
        "//third_party/go:github.com__grafana-tools__sdk",
    ],
)
