// Code generated by protoc-gen-api. DO NOT EDIT.
// source: malonaz/test/user/v1/organization.proto
package model

import (
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	v1 "github.com/malonaz/core/genproto/test/user/v1"
	resourcename "go.einride.tech/aip/resourcename"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

var ErrOrganizationAlreadyExists = errors.New("organization already exists")
var ErrOrganizationNotExist = errors.New("organization does not exist")
var ErrOrganizationAlreadyDeleted = errors.New("organization already deleted")
var ErrOrganizationETagChanged = errors.New("organization etag changed")

type Organization struct {
	OrganizationID string     `db:"organization_id" schema:"public" table:"organization"`
	CreateTime     time.Time  `db:"create_time" schema:"public" table:"organization"`
	UpdateTime     time.Time  `db:"update_time" schema:"public" table:"organization"`
	DeleteTime     *time.Time `db:"delete_time" schema:"public" table:"organization"`
	DisplayName    string     `db:"display_name" schema:"public" table:"organization"`
	Labels         []byte     `db:"labels" schema:"public" table:"organization"`
	Etag           string     `db:"etag" schema:"public" table:"organization"`
}

func OrganizationFromPb(m *v1.Organization) (*Organization, error) {
	if m.Name == "" {
		return nil, fmt.Errorf("FromPb requires `name` to be set")
	}

	OrganizationID, err := ParseOrganizationName(m.Name)
	if err != nil {
		return nil, err
	}

	if err := m.CreateTime.CheckValid(); err != nil {
		return nil, fmt.Errorf("validating create_time: %w", err)
	}
	if err := m.UpdateTime.CheckValid(); err != nil {
		return nil, fmt.Errorf("validating update_time: %w", err)
	}
	var DeleteTime *time.Time
	if m.DeleteTime != nil {
		if err := m.DeleteTime.CheckValid(); err != nil {
			return nil, fmt.Errorf("validating delete_time: %w", err)
		}
		t := m.DeleteTime.AsTime()
		DeleteTime = &t
	}
	var LabelsBytes []byte
	if m.Labels != nil {
		var err error
		LabelsBytes, err = json.Marshal(m.Labels)
		if err != nil {
			return nil, fmt.Errorf("marshaling Labels: %w", err)
		}
	}
	return &Organization{
		OrganizationID: OrganizationID,
		CreateTime:     m.CreateTime.AsTime(),
		UpdateTime:     m.UpdateTime.AsTime(),
		DeleteTime:     DeleteTime,
		DisplayName:    m.DisplayName,
		Labels:         LabelsBytes,
		Etag:           m.Etag,
	}, nil
}

func (m *Organization) ToPb() (*v1.Organization, error) {
	var CreateTime *timestamppb.Timestamp
	CreateTime = timestamppb.New(m.CreateTime)
	if err := CreateTime.CheckValid(); err != nil {
		return nil, fmt.Errorf("validating create_time: %w", err)
	}
	var UpdateTime *timestamppb.Timestamp
	UpdateTime = timestamppb.New(m.UpdateTime)
	if err := UpdateTime.CheckValid(); err != nil {
		return nil, fmt.Errorf("validating update_time: %w", err)
	}
	var DeleteTime *timestamppb.Timestamp
	if m.DeleteTime != nil {
		DeleteTime = timestamppb.New(*m.DeleteTime)
		if err := DeleteTime.CheckValid(); err != nil {
			return nil, fmt.Errorf("validating delete_time: %w", err)
		}
	}
	var Labels map[string]string
	if m.Labels != nil {
		Labels = map[string]string{}
		if err := json.Unmarshal(m.Labels, &Labels); err != nil {
			return nil, fmt.Errorf("unmarshaling Labels: %w", err)
		}
	}
	name := resourcename.Sprint("organizations/{organization}", m.OrganizationID)
	if err := resourcename.Validate(name); err != nil {
		return nil, fmt.Errorf("validating resource name: %w", err)
	}
	return &v1.Organization{
		Name:        name,
		CreateTime:  CreateTime,
		UpdateTime:  UpdateTime,
		DeleteTime:  DeleteTime,
		DisplayName: m.DisplayName,
		Labels:      Labels,
		Etag:        m.Etag,
	}, nil
}

func ParseOrganizationName(name string) (string, error) {
	var OrganizationID string
	if err := resourcename.Sscan(name, "organizations/{organization}", &OrganizationID); err != nil {
		return "", fmt.Errorf("parsing resource name: %v", err)
	}
	return OrganizationID, nil
}
