// Code generated by protoc-gen-api. DO NOT EDIT.
// source: malonaz/scheduler/v1/labels.proto
package v1

type LabelRetried struct {
	GetKey func() string
	True   string
}

type LabelSchedule struct {
	GetKey func() string
}

type LabelSet struct {
	Retried  LabelRetried
	Schedule LabelSchedule
}

var Labels = LabelSet{
	Retried: LabelRetried{
		GetKey: func() string {
			return "scheduler.malonaz.com/retried"
		},
		True: "true",
	},
	Schedule: LabelSchedule{
		GetKey: func() string {
			return "scheduler.malonaz.com/schedule"
		},
	},
}
