// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: malonaz/agent/v1/memory.proto

//go:build protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/malonaz/core/genproto/codegen/aip/v1"
	_ "github.com/malonaz/core/genproto/codegen/model/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Memory is one piece of an agent's long-term knowledge, distilled from its
// chats and tasks. Memories are the only thing that truly persists across
// chat rollovers: title and description form the cheap retrieval surface,
// content is loaded only after selection, and labels carry the agent-curated
// ontology. Written by the agent (via its create_memory tool) or by the
// compaction extraction turn; revised, merged and superseded over time rather
// than appended forever.
type Memory struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_CreateTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3"`
	xxx_hidden_UpdateTime  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3"`
	xxx_hidden_DeleteTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=delete_time,json=deleteTime,proto3"`
	xxx_hidden_Etag        string                 `protobuf:"bytes,5,opt,name=etag,proto3"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Title       string                 `protobuf:"bytes,7,opt,name=title,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,8,opt,name=description,proto3"`
	xxx_hidden_Content     *structpb.Value        `protobuf:"bytes,9,opt,name=content,proto3"`
	xxx_hidden_SourceChat  string                 `protobuf:"bytes,10,opt,name=source_chat,json=sourceChat,proto3"`
	xxx_hidden_SourceTask  string                 `protobuf:"bytes,11,opt,name=source_task,json=sourceTask,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_malonaz_agent_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_agent_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Memory) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Memory) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return nil
}

func (x *Memory) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return nil
}

func (x *Memory) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeleteTime
	}
	return nil
}

func (x *Memory) GetEtag() string {
	if x != nil {
		return x.xxx_hidden_Etag
	}
	return ""
}

func (x *Memory) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Memory) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *Memory) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Memory) GetContent() *structpb.Value {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *Memory) GetSourceChat() string {
	if x != nil {
		return x.xxx_hidden_SourceChat
	}
	return ""
}

func (x *Memory) GetSourceTask() string {
	if x != nil {
		return x.xxx_hidden_SourceTask
	}
	return ""
}

func (x *Memory) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Memory) SetCreateTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreateTime = v
}

func (x *Memory) SetUpdateTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdateTime = v
}

func (x *Memory) SetDeleteTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeleteTime = v
}

func (x *Memory) SetEtag(v string) {
	x.xxx_hidden_Etag = v
}

func (x *Memory) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *Memory) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *Memory) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Memory) SetContent(v *structpb.Value) {
	x.xxx_hidden_Content = v
}

func (x *Memory) SetSourceChat(v string) {
	x.xxx_hidden_SourceChat = v
}

func (x *Memory) SetSourceTask(v string) {
	x.xxx_hidden_SourceTask = v
}

func (x *Memory) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreateTime != nil
}

func (x *Memory) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateTime != nil
}

func (x *Memory) HasDeleteTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeleteTime != nil
}

func (x *Memory) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *Memory) ClearCreateTime() {
	x.xxx_hidden_CreateTime = nil
}

func (x *Memory) ClearUpdateTime() {
	x.xxx_hidden_UpdateTime = nil
}

func (x *Memory) ClearDeleteTime() {
	x.xxx_hidden_DeleteTime = nil
}

func (x *Memory) ClearContent() {
	x.xxx_hidden_Content = nil
}

type Memory_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource name of the memory.
	// Format: organizations/{organization}/users/{user}/agents/{agent}/memories/{memory}
	Name string
	// The creation timestamp of the memory.
	CreateTime *timestamppb.Timestamp
	// The last update timestamp of the memory.
	UpdateTime *timestamppb.Timestamp
	// The deletion timestamp of the memory. Set when soft-deleted.
	DeleteTime *timestamppb.Timestamp
	// A checksum computed by the server based on the current value of the resource.
	// Can be sent in update and delete requests to ensure the client has an
	// up-to-date value before proceeding.
	Etag string
	// The labels on this memory: the agent-curated ontology (e.g. kind of
	// memory, subject), evolving without schema migrations.
	Labels map[string]string
	// Short human-readable title, the primary retrieval surface.
	Title string
	// One-or-two-line description of the content, shown alongside search
	// matches and used for seed-time selection.
	Description string
	// The unstructured content of the memory.
	Content *structpb.Value
	// The chat this memory was distilled from, if any.
	// Format: organizations/{organization}/users/{user}/chats/{chat}
	SourceChat string
	// The task this memory was distilled from, if any.
	// Format: organizations/{organization}/users/{user}/agents/{agent}/tasks/{task}
	SourceTask string
}

func (b0 Memory_builder) Build() *Memory {
	m0 := &Memory{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_CreateTime = b.CreateTime
	x.xxx_hidden_UpdateTime = b.UpdateTime
	x.xxx_hidden_DeleteTime = b.DeleteTime
	x.xxx_hidden_Etag = b.Etag
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_SourceChat = b.SourceChat
	x.xxx_hidden_SourceTask = b.SourceTask
	return m0
}

var File_malonaz_agent_v1_memory_proto protoreflect.FileDescriptor

const file_malonaz_agent_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x1dmalonaz/agent/v1/memory.proto\x12\x10malonaz.agent.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a malonaz/codegen/aip/v1/aip.proto\x1a$malonaz/codegen/model/v1/model.proto\"\xca\a\n" +
	"\x06Memory\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12@\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12F\n" +
	"\vdelete_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\t\xe0A\x03\xba\xea\x0f\x02 \x01R\n" +
	"deleteTime\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\x12\xd2\x01\n" +
	"\x06labels\x18\x06 \x03(\v2$.malonaz.agent.v1.Memory.LabelsEntryB\x93\x01\xbaH\x87\x01\x9a\x01\x83\x01\x10@\"drb2`^([a-zA-Z0-9]([a-zA-Z0-9.-]{0,251}[a-zA-Z0-9])?/)?[a-zA-Z0-9]([a-zA-Z0-9_.-]{0,61}[a-zA-Z0-9])?$*\x19r\x17\x18?2\x13^[a-z0-9_\\-\\p{L}]*$\xba\xea\x0f\x04\x10\x01 \x01R\x06labels\x12!\n" +
	"\x05title\x18\a \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x18\x80\x04R\x05title\x12*\n" +
	"\vdescription\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\vdescription\x12>\n" +
	"\acontent\x18\t \x01(\v2\x16.google.protobuf.ValueB\f\xbaH\x03\xc8\x01\x01\xba\xea\x0f\x02\x10\x01R\acontent\x129\n" +
	"\vsource_chat\x18\n" +
	" \x01(\tB\x18\xfaA\x15\n" +
	"\x13ai.malonaz.com/ChatR\n" +
	"sourceChat\x12<\n" +
	"\vsource_task\x18\v \x01(\tB\x1b\xfaA\x18\n" +
	"\x16agent.malonaz.com/TaskR\n" +
	"sourceTask\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xae\x01\xeaAx\n" +
	"\x18agent.malonaz.com/Memory\x12Jorganizations/{organization}/users/{user}/agents/{agent}/memories/{memory}*\bmemories2\x06memoryҦ\x04\a\n" +
	"\x05agent\x82\xf6,$797bbe2e-086d-480d-b7fc-0bd4655d8d35B+Z)github.com/malonaz/core/genproto/agent/v1b\x06proto3"

var file_malonaz_agent_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_malonaz_agent_v1_memory_proto_goTypes = []any{
	(*Memory)(nil),                // 0: malonaz.agent.v1.Memory
	nil,                           // 1: malonaz.agent.v1.Memory.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 3: google.protobuf.Value
}
var file_malonaz_agent_v1_memory_proto_depIdxs = []int32{
	2, // 0: malonaz.agent.v1.Memory.create_time:type_name -> google.protobuf.Timestamp
	2, // 1: malonaz.agent.v1.Memory.update_time:type_name -> google.protobuf.Timestamp
	2, // 2: malonaz.agent.v1.Memory.delete_time:type_name -> google.protobuf.Timestamp
	1, // 3: malonaz.agent.v1.Memory.labels:type_name -> malonaz.agent.v1.Memory.LabelsEntry
	3, // 4: malonaz.agent.v1.Memory.content:type_name -> google.protobuf.Value
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_malonaz_agent_v1_memory_proto_init() }
func file_malonaz_agent_v1_memory_proto_init() {
	if File_malonaz_agent_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malonaz_agent_v1_memory_proto_rawDesc), len(file_malonaz_agent_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_malonaz_agent_v1_memory_proto_goTypes,
		DependencyIndexes: file_malonaz_agent_v1_memory_proto_depIdxs,
		MessageInfos:      file_malonaz_agent_v1_memory_proto_msgTypes,
	}.Build()
	File_malonaz_agent_v1_memory_proto = out.File
	file_malonaz_agent_v1_memory_proto_goTypes = nil
	file_malonaz_agent_v1_memory_proto_depIdxs = nil
}
