package postgres

import (
	"errors"
	"fmt"
	"strings"

	"github.com/huandu/xstrings"
	"google.golang.org/protobuf/compiler/protogen"

	modelpb "github.com/malonaz/core/genproto/codegen/model/v1"
	"github.com/malonaz/core/go/pbutil"
	"github.com/malonaz/core/tools/protoc-gen-core/plugin"
	"github.com/malonaz/core/tools/protoc-gen-core/resource"
	"github.com/malonaz/core/tools/protoc-gen-core/schema"
)

var (
	postgresPkg = protogen.GoImportPath("github.com/malonaz/core/go/postgres")
	pgxPkg      = protogen.GoImportPath("github.com/jackc/pgx/v5")
	fmtPkg      = protogen.GoImportPath("fmt")
	stringsPkg  = protogen.GoImportPath("strings")
	timePkg     = protogen.GoImportPath("time")
	contextPkg  = protogen.GoImportPath("context")

	storeGenerated bool
)

func ResetState() {
	storeGenerated = false
}

func Generate(file *protogen.File, g *protogen.GeneratedFile, packageName protogen.GoPackageName, opts *plugin.Opts) error {
	modelImportPath := opts.AdditionalGoImportPaths["model"]
	type modelMessage struct {
		message   *protogen.Message
		modelOpts *modelpb.ModelOpts
		pr        *resource.ParsedResource
	}

	var messages []modelMessage
	for _, message := range file.Messages {
		modelOpts, err := pbutil.GetExtension[*modelpb.ModelOpts](message.Desc.Options(), modelpb.E_ModelOpts)
		if err != nil {
			if errors.Is(err, pbutil.ErrExtensionNotFound) {
				continue
			}
			return fmt.Errorf("getting model_opts for %s: %w", message.GoIdent.GoName, err)
		}
		pr, err := resource.ParseFromMessage(message)
		if err != nil {
			return fmt.Errorf("parsing resource from message %s: %w", message.GoIdent.GoName, err)
		}
		messages = append(messages, modelMessage{message: message, modelOpts: modelOpts, pr: pr})
	}

	if len(messages) == 0 {
		g.Skip()
		return nil
	}

	gen := &generator{g: g, modelImportPath: modelImportPath}
	_ = gen.ident(contextPkg, "context")

	g.P("// Code generated by protoc-gen-api. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("package ", packageName)
	g.P()

	if !storeGenerated {
		storeGenerated = true
		g.P("// Store is this service's db layer.")
		g.P("type Store struct {")
		g.P("  client *", postgresPkg.Ident("Client"))
		g.P("}")
		g.P()
		g.P("// New returns a new db.")
		g.P("func New(client *", postgresPkg.Ident("Client"), ") *Store {")
		g.P("  return &Store{client: client}")
		g.P("}")
		g.P()
	}

	var msgCtxs []*msgCtx
	for _, mm := range messages {
		mc, err := gen.newMsgCtx(mm.message, mm.modelOpts, mm.pr)
		if err != nil {
			return fmt.Errorf("building context for %s: %w", mm.message.GoIdent.GoName, err)
		}
		msgCtxs = append(msgCtxs, mc)
	}

	g.P("var (")
	for _, mc := range msgCtxs {
		g.P("  ", mc.goType, "PostgresColumns = ", postgresPkg.Ident("GetDBColumns"), "(", modelImportPath.Ident(mc.goType), "{})")
		if mc.hasJoins {
			exceptArgs := mc.exceptColumnsArgs()
			g.P("  ", mc.goType, "WritePostgresColumns = ", postgresPkg.Ident("GetDBColumns"), "(", modelImportPath.Ident(mc.goType), "{}, ", postgresPkg.Ident("ExceptColumns"), "(", exceptArgs, "))")
		}
	}
	g.P(")")
	g.P()

	for _, mc := range msgCtxs {
		if mc.hasJoins {
			mc.generateJoinVars()
		}
		mc.generateETagGetter()
		mc.generateInsertVars()
		mc.generateInsert()
		mc.generateWithRequestIDStruct()
		mc.generateInsertIdempotently()
		mc.generateUpdate()
		mc.generateDelete()
		mc.generateGet()
		mc.generateBatchGet()
		mc.generateList()
	}

	return nil
}

type generator struct {
	g               *protogen.GeneratedFile
	modelImportPath protogen.GoImportPath
}

func (gen *generator) ident(path protogen.GoImportPath, name string) string {
	return gen.g.QualifiedGoIdent(protogen.GoIdent{GoName: name, GoImportPath: path})
}

func (gen *generator) modelIdent(name string) string {
	return gen.ident(gen.modelImportPath, name)
}

// childCtx precomputes the codegen inputs for a persisted singleton child.
type childCtx struct {
	schema.SingletonChild
	goType           string // Go type of the child model.
	paramName        string // Go parameter name for the child model.
	tableName        string // Qualified table name.
	placeholderDecls string // WHERE conditions binding the child to its parent's identifiers.
	writeColumnsVar  string // Columns var to use when the child has joined columns; empty otherwise.
}

func (gen *generator) newChildCtx(child schema.SingletonChild) (*childCtx, error) {
	bindings, err := schema.ColumnBindings(child.Pattern, child.ModelOpts)
	if err != nil {
		return nil, err
	}
	conditions := make([]string, len(bindings))
	for i, binding := range bindings {
		conditions[i] = fmt.Sprintf("%s = $%d", binding.Column, i+1)
	}

	joins, err := schema.ParseJoins(child.Message)
	if err != nil {
		return nil, fmt.Errorf("parsing joins for singleton child %s: %w", child.Message.GoIdent.GoName, err)
	}
	writeColumnsVar := ""
	if len(joins) > 0 {
		writeColumnsVar = child.Message.GoIdent.GoName + "WritePostgresColumns"
	}

	return &childCtx{
		SingletonChild:   child,
		goType:           child.Message.GoIdent.GoName,
		paramName:        untitle(xstrings.ToCamelCase(child.Resource.Desc.Singular)),
		tableName:        child.Table().Qualified(),
		placeholderDecls: strings.Join(conditions, " AND "),
		writeColumnsVar:  writeColumnsVar,
	}, nil
}

type msgCtx struct {
	gen *generator
	g   *protogen.GeneratedFile

	message   *protogen.Message
	modelOpts *modelpb.ModelOpts
	pr        *resource.ParsedResource

	multiPattern bool
	singleton    bool

	goType  string
	goName  string
	goParam string

	goTypeFqi         string
	errNotExist       string
	errAlreadyExists  string
	errAlreadyDeleted string
	errETagChanged    string

	columnBindings   []schema.ColumnBinding
	parentBindings   []schema.ColumnBinding
	tableName        string
	bareTableName    string
	whereClause      string
	placeholderDecls string
	columnNames      string
	identifier       string

	hasEtag       bool
	hasDeleteTime bool

	singletonChildren []*childCtx

	hasJoins bool
	joins    []schema.Join

	joinSubqueryExpr string
	joinSelectExprs  string
	joinClause       string
}

func (gen *generator) newMsgCtx(message *protogen.Message, modelOpts *modelpb.ModelOpts, pr *resource.ParsedResource) (*msgCtx, error) {
	goType := message.GoIdent.GoName
	goName := untitle(goType)

	multiPattern := len(pr.Patterns) > 1
	singleton := false
	if !multiPattern {
		singleton = pr.Patterns[0].Singleton
	}

	table := schema.TableOf(pr, modelOpts)
	bindings, err := schema.UnionColumnBindings(pr, modelOpts)
	if err != nil {
		return nil, err
	}

	var whereConditions, placeholderConditions []string
	for i, binding := range bindings {
		whereConditions = append(whereConditions, fmt.Sprintf("%s = $%%d", binding.Column))
		placeholderConditions = append(placeholderConditions, fmt.Sprintf("%s = $%d", binding.Column, i+1))
	}

	identifier := ""
	if !singleton && len(bindings) > 0 {
		identifier = bindings[len(bindings)-1].Column
	}

	// Parent identifiers: a singleton's identity is exactly its parent's; a
	// collection resource's parent identifiers are everything but its own.
	var parentBindings []schema.ColumnBinding
	if singleton {
		parentBindings = bindings
	} else if len(bindings) > 1 {
		parentBindings = bindings[:len(bindings)-1]
	}

	children, err := schema.SingletonChildren(message, pr)
	if err != nil {
		return nil, err
	}
	singletonChildren := make([]*childCtx, 0, len(children))
	for _, child := range children {
		cc, err := gen.newChildCtx(child)
		if err != nil {
			return nil, err
		}
		singletonChildren = append(singletonChildren, cc)
	}

	joins, err := schema.ParseJoins(message)
	if err != nil {
		return nil, fmt.Errorf("parsing joins for %s: %w", goType, err)
	}
	hasJoins := len(joins) > 0

	if multiPattern {
		if hasJoins {
			return nil, fmt.Errorf("multi-pattern resource %s cannot declare joins", goType)
		}
		if len(singletonChildren) > 0 {
			return nil, fmt.Errorf("multi-pattern resource %s cannot have singleton children", goType)
		}
	}

	var joinSubqueryExpr, joinSelectExprs, joinClauseStr string
	if hasJoins {
		joinSubqueryExpr = buildJoinSubqueryExpr(joins, table.Name)
		joinSelectExprs = buildJoinSelectExprs(joins)
		joinClauseStr = buildJoinClause(joins, table.Name)
	}

	return &msgCtx{
		gen:     gen,
		g:       gen.g,
		message: message, modelOpts: modelOpts, pr: pr,

		multiPattern: multiPattern,
		singleton:    singleton,

		goType:  goType,
		goName:  goName,
		goParam: "_" + goName,

		goTypeFqi:         gen.modelIdent(goType),
		errNotExist:       gen.modelIdent("Err" + goType + "NotExist"),
		errAlreadyExists:  gen.modelIdent("Err" + goType + "AlreadyExists"),
		errAlreadyDeleted: gen.modelIdent("Err" + goType + "AlreadyDeleted"),
		errETagChanged:    gen.modelIdent("Err" + goType + "ETagChanged"),

		columnBindings:   bindings,
		parentBindings:   parentBindings,
		tableName:        table.Qualified(),
		bareTableName:    table.Name,
		whereClause:      strings.Join(whereConditions, " AND "),
		placeholderDecls: strings.Join(placeholderConditions, " AND "),
		columnNames:      strings.Join(schema.Columns(bindings), ", "),
		identifier:       identifier,

		hasEtag:       message.Desc.Fields().ByName("etag") != nil,
		hasDeleteTime: message.Desc.Fields().ByName("delete_time") != nil,

		singletonChildren: singletonChildren,

		hasJoins:         hasJoins,
		joins:            joins,
		joinSubqueryExpr: joinSubqueryExpr,
		joinSelectExprs:  joinSelectExprs,
		joinClause:       joinClauseStr,
	}, nil
}

func buildJoinSubqueryExpr(joins []schema.Join, childBareTable string) string {
	var parts []string
	for _, join := range joins {
		var whereParts []string
		for _, condition := range join.Conditions {
			whereParts = append(whereParts, fmt.Sprintf("%s.%s = %s.%s", join.Table.Name, condition.ParentColumn, childBareTable, condition.ChildColumn))
		}
		whereClause := strings.Join(whereParts, " AND ")
		for _, field := range join.Fields {
			parts = append(parts, fmt.Sprintf("(SELECT %s.%s FROM %s WHERE %s) AS %s",
				join.Table.Name, field.Column, join.Table.Qualified(), whereClause, field.Alias))
		}
	}
	return "," + strings.Join(parts, ",")
}

func buildJoinSelectExprs(joins []schema.Join) string {
	var parts []string
	for _, join := range joins {
		for _, field := range join.Fields {
			parts = append(parts, fmt.Sprintf("%s.%s AS %s", join.Table.Name, field.Column, field.Alias))
		}
	}
	return "," + strings.Join(parts, ",")
}

func buildJoinClause(joins []schema.Join, childBareTable string) string {
	var parts []string
	for _, join := range joins {
		var onParts []string
		for _, condition := range join.Conditions {
			onParts = append(onParts, fmt.Sprintf("%s.%s = %s.%s", join.Table.Name, condition.ParentColumn, childBareTable, condition.ChildColumn))
		}
		parts = append(parts, fmt.Sprintf("INNER JOIN %s ON %s", join.Table.Qualified(), strings.Join(onParts, " AND ")))
	}
	return strings.Join(parts, " ")
}

func (mc *msgCtx) exceptColumnsArgs() string {
	var args []string
	for _, join := range mc.joins {
		for _, field := range join.Fields {
			args = append(args, fmt.Sprintf("%q", field.Alias))
		}
	}
	return strings.Join(args, ", ")
}

func (mc *msgCtx) generateJoinVars() {
	g := mc.g
	g.P(fmt.Sprintf("var %sJoinSubqueryExpr = `%s`", mc.goName, mc.joinSubqueryExpr))
	g.P(fmt.Sprintf("var %sJoinSelectExprs = `%s`", mc.goName, mc.joinSelectExprs))
	g.P(fmt.Sprintf("var %sJoinClause = `%s`", mc.goName, mc.joinClause))
	g.P()
}

func (mc *msgCtx) writeColumns() string {
	if mc.hasJoins {
		return mc.goType + "WritePostgresColumns"
	}
	return mc.goType + "PostgresColumns"
}

func (mc *msgCtx) returningExpr(columnsVar string) string {
	expr := fmt.Sprintf("%s(\"%%s\", %s)", mc.postgres("SelectQuery"), columnsVar)
	if mc.hasJoins {
		expr += fmt.Sprintf(" + %sJoinSubqueryExpr", mc.goName)
	}
	return expr
}

func (mc *msgCtx) pgx(name string) string      { return mc.gen.ident(pgxPkg, name) }
func (mc *msgCtx) postgres(name string) string { return mc.gen.ident(postgresPkg, name) }
func (mc *msgCtx) fmtI(name string) string     { return mc.gen.ident(fmtPkg, name) }
func (mc *msgCtx) stringsI(name string) string { return mc.gen.ident(stringsPkg, name) }

// idParamName returns the Go parameter name of an identifier, e.g. "shelfId".
func idParamName(binding schema.ColumnBinding) string {
	return untitle(xstrings.ToCamelCase(binding.Variable)) + "Id"
}

func (mc *msgCtx) patternVarIDsGoTrue() string {
	parts := make([]string, len(mc.columnBindings))
	for i, binding := range mc.columnBindings {
		parts[i] = idParamName(binding)
	}
	return strings.Join(parts, ", ")
}

func (mc *msgCtx) patternVarFieldAccess() string {
	parts := make([]string, len(mc.columnBindings))
	for i, binding := range mc.columnBindings {
		parts[i] = fmt.Sprintf("%s.%s", mc.goParam, binding.GoFieldName())
	}
	return strings.Join(parts, ", ")
}

func (mc *msgCtx) patternVarIDUntitled() string {
	return mc.patternVarIDsGoTrue()
}

func (mc *msgCtx) qualifiedPlaceholderDecls() string {
	if !mc.hasJoins {
		return mc.placeholderDecls
	}
	conditions := make([]string, len(mc.columnBindings))
	for i, binding := range mc.columnBindings {
		conditions[i] = fmt.Sprintf("%s.%s = $%d", mc.bareTableName, binding.Column, i+1)
	}
	return strings.Join(conditions, " AND ")
}

// emitIDConditionAppends emits code appending WHERE conditions and params for
// each identifier column. Non-shared identifiers with an empty value are
// matched against NULL, since only the identifiers of the pattern a row was
// created under are populated. Expects `conditions []string` and `params
// []any` to be in scope.
func (mc *msgCtx) emitIDConditionAppends(indent string, exprFor func(schema.ColumnBinding) string) {
	g := mc.g
	for _, binding := range mc.columnBindings {
		expr := exprFor(binding)
		if binding.Shared {
			g.P(indent, "params = append(params, ", expr, ")")
			g.P(indent, "conditions = append(conditions, ", mc.fmtI("Sprintf"), "(\"", binding.Column, " = $%d\", len(params)))")
		} else {
			g.P(indent, "if ", expr, " != \"\" {")
			g.P(indent, "  params = append(params, ", expr, ")")
			g.P(indent, "  conditions = append(conditions, ", mc.fmtI("Sprintf"), "(\"", binding.Column, " = $%d\", len(params)))")
			g.P(indent, "} else {")
			g.P(indent, "  conditions = append(conditions, \"", binding.Column, " IS NULL\")")
			g.P(indent, "}")
		}
	}
}

func (mc *msgCtx) generateETagGetter() {
	if !mc.hasEtag {
		return
	}
	g := mc.g
	g.P(fmt.Sprintf("func (s *Store) get%sETag(ctx context.Context, %s string) (string, error) {", mc.goType, mc.patternVarIDsGoTrue()))
	if mc.multiPattern {
		g.P(fmt.Sprintf("  conditions := make([]string, 0, %d)", len(mc.columnBindings)))
		g.P(fmt.Sprintf("  params := make([]any, 0, %d)", len(mc.columnBindings)))
		mc.emitIDConditionAppends("  ", idParamName)
		g.P(fmt.Sprintf("  query := %s(\"SELECT etag FROM %s WHERE %%s\", %s(conditions, \" AND \"))",
			mc.fmtI("Sprintf"), mc.tableName, mc.stringsI("Join")))
		g.P("  rows, err := s.client.Query(ctx, query, params...)")
	} else {
		g.P(fmt.Sprintf("  query := `SELECT etag FROM %s WHERE %s`", mc.tableName, mc.placeholderDecls))
		g.P(fmt.Sprintf("  rows, err := s.client.Query(ctx, query, %s)", mc.patternVarIDsGoTrue()))
	}
	g.P("  if err != nil {")
	g.P("    return \"\", err")
	g.P("  }")
	g.P(fmt.Sprintf("  return %s(rows, %s[string])", mc.pgx("CollectOneRow"), mc.pgx("RowTo")))
	g.P("}")
	g.P()
}

func (mc *msgCtx) generateETagCheck(operation string, patternVarArgs string, inTransaction bool) {
	g := mc.g
	retPrefix := "return nil, "
	if inTransaction {
		retPrefix = "return "
	}
	g.P("      if etag != \"\" {")
	g.P(fmt.Sprintf("        currentEtag, getEtagErr := s.get%sETag(ctx, %s)", mc.goType, patternVarArgs))
	g.P("        switch getEtagErr {")
	g.P("        case nil:")
	g.P("          if currentEtag == etag {")
	g.P("            ", retPrefix, mc.fmtI("Errorf"), "(\"", operation, " matched no rows but etag unchanged: expected etag mismatch\")")
	g.P("          }")
	g.P(fmt.Sprintf("          %s%s", retPrefix, mc.errETagChanged))
	g.P(fmt.Sprintf("        case %s:", mc.pgx("ErrNoRows")))
	g.P(fmt.Sprintf("          %s%s", retPrefix, mc.errNotExist))
	g.P("        default:")
	g.P("          ", retPrefix, mc.fmtI("Errorf"), "(\"getting etag: %v\", getEtagErr)")
	g.P("        }")
	g.P("      }")
}

func untitle(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
