package(default_visibility = ["PUBLIC"])

export_file(
    name = "model",
    src = "model.tmpl",
)

export_file(
    name = "db",
    src = "db.tmpl",
)

export_file(
    name = "rpc",
    src = "rpc.tmpl",
)

export_file(
    name = "llm",
    src = "llm.tmpl",
)

export_file(
    name = "gateway_handler.go.tmpl",
    src = "gateway_handler.go.tmpl",
)
