package(default_visibility = ["PUBLIC"])

export_file(
    name = "model",
    src = "model.tmpl",
)

export_file(
    name = "rpc",
    src = "rpc.tmpl",
)

export_file(
    name = "postgres",
    src = "postgres.tmpl",
)

export_file(
    name = "llm",
    src = "llm.tmpl",
)

export_file(
    name = "gateway_handler",
    src = "gateway_handler.tmpl",
)
