proto_library(
    name = "v1",
    srcs = ["llm.proto"],
    additional_context = {
        GO_IMPORT_PATH: "github.com/malonaz/core/genproto/codegen/llm/v1",
    },
    root_dir = "proto",
    visibility = ["PUBLIC"],
)
