proto_library(
    name = "v1",
    srcs = ["aip.proto"],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/proto:google__api__expr__v1alpha1",
        "//third_party/proto:validate",
    ],
)
