grpc_library(
    name = "v1",
    srcs = ["scheduler_service.proto"],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/proto:core__codegen__aip__v1",
        "//third_party/proto:core__codegen__model__v1",
        "//third_party/proto:core__scheduler__v1",
        "//third_party/proto:google__api__annotations",
        "//third_party/proto:google__api__expr__v1alpha1",
        "//third_party/proto:validate",
    ],
)
