proto_library(
    name = "v1",
    srcs = ["canonicalize.proto"],
    additional_context = {
        GO_IMPORT_PATH: "github.com/malonaz/core/genproto/canonicalize/v1",
    },
    labels = ["copy_generated_code"],
    visibility = ["PUBLIC"],
)
