proto_library(
    name = "v1",
    srcs = ["audio.proto"],
    additional_context = {
        GO_IMPORT_PATH: "github.com/malonaz/core/genproto/audio/v1",
    },
    root_dir = "proto",
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/proto:validate",
    ],
)
