CREATE TABLE message (
    request_id UUID NOT NULL,
    organization_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    chat_id TEXT NOT NULL,
    message_id TEXT NOT NULL,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    delete_time TIMESTAMP,
    etag TEXT NOT NULL,
    labels JSONB,
    annotations BYTEA,
    role SMALLINT NOT NULL,
    blocks JSONB NOT NULL,
    model TEXT,
    model_usage JSONB,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    status JSONB,
    PRIMARY KEY (organization_id, user_id, chat_id, message_id),
    CONSTRAINT message_request_id_unique UNIQUE (request_id)
);
