go_library(
    name = "routine",
    srcs = [
        "metrics.go",
        "routine.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:github.com__cenkalti__backoff__v4",
        "//third_party/go:github.com__prometheus__client_golang__prometheus",
        "//third_party/go:github.com__prometheus__client_golang__prometheus__promauto",
    ],
)
