go_library(
    name = "scheduler",
    srcs = ["scheduler.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//go/aip",
        "//go/uuid",
        "//malonaz/scheduler/scheduler_service/v1",
        "//malonaz/scheduler/v1",
        "//third_party/go:google.golang.org__grpc__metadata",
        "//third_party/go:google.golang.org__protobuf__proto",
        "//third_party/go:google.golang.org__protobuf__types__known__anypb",
        "//third_party/go:google.golang.org__protobuf__types__known__timestamppb",
    ],
)
