package(default_visibility = ["PUBLIC"])

export_file(
    name = "migrations_test.go.tmpl",
    src = "migrations_test.go.tmpl",
)

export_file(
    name = "migrations_sat_test.go.tmpl",
    src = "migrations_sat_test.go.tmpl",
)
