package(default_visibility = ["PUBLIC"])

export_file(
    name = "postgres_migrator.go.tmpl",
    src = "postgres_migrator.go.tmpl",
)

export_file(
    name = "postgres_initializer.go.tmpl",
    src = "postgres_initializer.go.tmpl",
)

export_file(
    name = "postgres_migrator_test.go.tmpl",
    src = "postgres_migrator_test.go.tmpl",
)

export_file(
    name = "postgres_reset.go.tmpl",
    src = "postgres_reset.go.tmpl",
)
