go_library(
    name = "migrations",
    srcs = ["migrations.go"],
    visibility = ["//..."],
    deps = [
        "//go/logging",
        "//third_party/go:github.com__pkg__errors",
        "//third_party/go:gopkg.in__yaml.v2",
    ],
)
