proto_library(
    name = "v1",
    srcs = ["authentication.proto"],
    additional_context = {
        GO_IMPORT_PATH: "github.com/malonaz/core/genproto/authentication/v1",
    },
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/proto:validate",
    ],
)
