go_library(
    name = "binary",
    srcs = [
        "binary.go",
        "worker.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//go/logging",
        "//third_party/go:github.com__hashicorp__go-multierror",
    ],
)
