go_library(
    name = "flags",
    srcs = ["flags.go"],
    visibility = ["//..."],
    deps = [
        "//go/logging",
        "//third_party/go:github.com__jessevdk__go-flags",
        "//third_party/go:github.com__pkg__errors",
    ],
)
