// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file malonaz/ai/genui/v1/component.proto (package malonaz.ai.genui.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { ActionRow, ActionRowValid, Chart, ChartValid, KeyValueList, KeyValueListValid, Table, TableValid, Text, TextValid, Timeline, TimelineValid } from "./content_pb";
import { file_malonaz_ai_genui_v1_content } from "./content_pb";
import type { Choice, ChoiceValid, Confirmation, ConfirmationValid, DateTimePicker, DateTimePickerValid, Form, FormValid, MultiChoice, MultiChoiceValid, ResourcePicker, ResourcePickerValid, Slider, SliderValid } from "./input_pb";
import { file_malonaz_ai_genui_v1_input } from "./input_pb";
import type { ResourceCard, ResourceCardValid, ResourceList, ResourceListValid } from "./resource_pb";
import { file_malonaz_ai_genui_v1_resource } from "./resource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file malonaz/ai/genui/v1/component.proto.
 */
export const file_malonaz_ai_genui_v1_component: GenFile = /*@__PURE__*/
  fileDesc("CiNtYWxvbmF6L2FpL2dlbnVpL3YxL2NvbXBvbmVudC5wcm90bxITbWFsb25hei5haS5nZW51aS52MSLBBgoJQ29tcG9uZW50EikKBHRleHQYASABKAsyGS5tYWxvbmF6LmFpLmdlbnVpLnYxLlRleHRIABI7Cg5rZXlfdmFsdWVfbGlzdBgCIAEoCzIhLm1hbG9uYXouYWkuZ2VudWkudjEuS2V5VmFsdWVMaXN0SAASMQoIdGltZWxpbmUYAyABKAsyHS5tYWxvbmF6LmFpLmdlbnVpLnYxLlRpbWVsaW5lSAASKwoFY2hhcnQYBCABKAsyGi5tYWxvbmF6LmFpLmdlbnVpLnYxLkNoYXJ0SAASKwoFdGFibGUYBSABKAsyGi5tYWxvbmF6LmFpLmdlbnVpLnYxLlRhYmxlSAASOgoNcmVzb3VyY2VfY2FyZBgGIAEoCzIhLm1hbG9uYXouYWkuZ2VudWkudjEuUmVzb3VyY2VDYXJkSAASOgoNcmVzb3VyY2VfbGlzdBgHIAEoCzIhLm1hbG9uYXouYWkuZ2VudWkudjEuUmVzb3VyY2VMaXN0SAASNAoKYWN0aW9uX3JvdxgIIAEoCzIeLm1hbG9uYXouYWkuZ2VudWkudjEuQWN0aW9uUm93SAASLQoGY2hvaWNlGAkgASgLMhsubWFsb25hei5haS5nZW51aS52MS5DaG9pY2VIABI4CgxtdWx0aV9jaG9pY2UYCiABKAsyIC5tYWxvbmF6LmFpLmdlbnVpLnYxLk11bHRpQ2hvaWNlSAASOQoMY29uZmlybWF0aW9uGAsgASgLMiEubWFsb25hei5haS5nZW51aS52MS5Db25maXJtYXRpb25IABIpCgRmb3JtGAwgASgLMhkubWFsb25hei5haS5nZW51aS52MS5Gb3JtSAASPgoPcmVzb3VyY2VfcGlja2VyGA0gASgLMiMubWFsb25hei5haS5nZW51aS52MS5SZXNvdXJjZVBpY2tlckgAEi0KBnNsaWRlchgOIAEoCzIbLm1hbG9uYXouYWkuZ2VudWkudjEuU2xpZGVySAASPwoQZGF0ZV90aW1lX3BpY2tlchgPIAEoCzIjLm1hbG9uYXouYWkuZ2VudWkudjEuRGF0ZVRpbWVQaWNrZXJIAEISCgljb21wb25lbnQSBbpIAggBQi5aLGdpdGh1Yi5jb20vbWFsb25hei9jb3JlL2dlbnByb3RvL2FpL2dlbnVpL3YxYgZwcm90bzM", [file_buf_validate_validate, file_malonaz_ai_genui_v1_content, file_malonaz_ai_genui_v1_input, file_malonaz_ai_genui_v1_resource]);

/**
 * Application-side envelope: the server wraps each parsed tool call into a
 * Component before streaming it to clients. The AI never sees this type —
 * each component message is exposed to the model as its own tool, so the
 * tool name identifies the variant before any field streams.
 *
 * Components split into two families:
 * - Display (content.proto, resource.proto): rendered and acknowledged;
 *   the agentic loop continues.
 * - Input (input.proto): ends the turn; the user's answer round-trips as a
 *   tool_result carrying an [InputResponse][malonaz.ai.genui.v1.InputResponse].
 *
 * @generated from message malonaz.ai.genui.v1.Component
 */
export type Component = Message<"malonaz.ai.genui.v1.Component"> & {
  /**
   * The component to render.
   *
   * @generated from oneof malonaz.ai.genui.v1.Component.component
   */
  component: {
    /**
     * Markdown-subset prose.
     *
     * @generated from field: malonaz.ai.genui.v1.Text text = 1;
     */
    value: Text;
    case: "text";
  } | {
    /**
     * Label/value facts.
     *
     * @generated from field: malonaz.ai.genui.v1.KeyValueList key_value_list = 2;
     */
    value: KeyValueList;
    case: "keyValueList";
  } | {
    /**
     * Ordered events.
     *
     * @generated from field: malonaz.ai.genui.v1.Timeline timeline = 3;
     */
    value: Timeline;
    case: "timeline";
  } | {
    /**
     * A chart of aggregates.
     *
     * @generated from field: malonaz.ai.genui.v1.Chart chart = 4;
     */
    value: Chart;
    case: "chart";
  } | {
    /**
     * Tabular data.
     *
     * @generated from field: malonaz.ai.genui.v1.Table table = 5;
     */
    value: Table;
    case: "table";
  } | {
    /**
     * A rich card for a single resource.
     *
     * @generated from field: malonaz.ai.genui.v1.ResourceCard resource_card = 6;
     */
    value: ResourceCard;
    case: "resourceCard";
  } | {
    /**
     * A list of resources rendered as compact rows.
     *
     * @generated from field: malonaz.ai.genui.v1.ResourceList resource_list = 7;
     */
    value: ResourceList;
    case: "resourceList";
  } | {
    /**
     * Client-side buttons: navigation, clipboard, external links.
     *
     * @generated from field: malonaz.ai.genui.v1.ActionRow action_row = 8;
     */
    value: ActionRow;
    case: "actionRow";
  } | {
    /**
     * A question with constrained answers.
     *
     * @generated from field: malonaz.ai.genui.v1.Choice choice = 9;
     */
    value: Choice;
    case: "choice";
  } | {
    /**
     * A question allowing several answers.
     *
     * @generated from field: malonaz.ai.genui.v1.MultiChoice multi_choice = 10;
     */
    value: MultiChoice;
    case: "multiChoice";
  } | {
    /**
     * An approve/reject gate for a consequential action.
     *
     * @generated from field: malonaz.ai.genui.v1.Confirmation confirmation = 11;
     */
    value: Confirmation;
    case: "confirmation";
  } | {
    /**
     * Structured multi-field input.
     *
     * @generated from field: malonaz.ai.genui.v1.Form form = 12;
     */
    value: Form;
    case: "form";
  } | {
    /**
     * Select one or more resources from candidates.
     *
     * @generated from field: malonaz.ai.genui.v1.ResourcePicker resource_picker = 13;
     */
    value: ResourcePicker;
    case: "resourcePicker";
  } | {
    /**
     * Bounded numeric input.
     *
     * @generated from field: malonaz.ai.genui.v1.Slider slider = 14;
     */
    value: Slider;
    case: "slider";
  } | {
    /**
     * A calendar/clock input.
     *
     * @generated from field: malonaz.ai.genui.v1.DateTimePicker date_time_picker = 15;
     */
    value: DateTimePicker;
    case: "dateTimePicker";
  } | { case: undefined; value?: undefined };
};

/**
 * Application-side envelope: the server wraps each parsed tool call into a
 * Component before streaming it to clients. The AI never sees this type —
 * each component message is exposed to the model as its own tool, so the
 * tool name identifies the variant before any field streams.
 *
 * Components split into two families:
 * - Display (content.proto, resource.proto): rendered and acknowledged;
 *   the agentic loop continues.
 * - Input (input.proto): ends the turn; the user's answer round-trips as a
 *   tool_result carrying an [InputResponse][malonaz.ai.genui.v1.InputResponse].
 *
 * @generated from message malonaz.ai.genui.v1.Component
 */
export type ComponentValid = Message<"malonaz.ai.genui.v1.Component"> & {
  /**
   * The component to render.
   *
   * @generated from oneof malonaz.ai.genui.v1.Component.component
   */
  component: {
    /**
     * Markdown-subset prose.
     *
     * @generated from field: malonaz.ai.genui.v1.Text text = 1;
     */
    value: TextValid;
    case: "text";
  } | {
    /**
     * Label/value facts.
     *
     * @generated from field: malonaz.ai.genui.v1.KeyValueList key_value_list = 2;
     */
    value: KeyValueListValid;
    case: "keyValueList";
  } | {
    /**
     * Ordered events.
     *
     * @generated from field: malonaz.ai.genui.v1.Timeline timeline = 3;
     */
    value: TimelineValid;
    case: "timeline";
  } | {
    /**
     * A chart of aggregates.
     *
     * @generated from field: malonaz.ai.genui.v1.Chart chart = 4;
     */
    value: ChartValid;
    case: "chart";
  } | {
    /**
     * Tabular data.
     *
     * @generated from field: malonaz.ai.genui.v1.Table table = 5;
     */
    value: TableValid;
    case: "table";
  } | {
    /**
     * A rich card for a single resource.
     *
     * @generated from field: malonaz.ai.genui.v1.ResourceCard resource_card = 6;
     */
    value: ResourceCardValid;
    case: "resourceCard";
  } | {
    /**
     * A list of resources rendered as compact rows.
     *
     * @generated from field: malonaz.ai.genui.v1.ResourceList resource_list = 7;
     */
    value: ResourceListValid;
    case: "resourceList";
  } | {
    /**
     * Client-side buttons: navigation, clipboard, external links.
     *
     * @generated from field: malonaz.ai.genui.v1.ActionRow action_row = 8;
     */
    value: ActionRowValid;
    case: "actionRow";
  } | {
    /**
     * A question with constrained answers.
     *
     * @generated from field: malonaz.ai.genui.v1.Choice choice = 9;
     */
    value: ChoiceValid;
    case: "choice";
  } | {
    /**
     * A question allowing several answers.
     *
     * @generated from field: malonaz.ai.genui.v1.MultiChoice multi_choice = 10;
     */
    value: MultiChoiceValid;
    case: "multiChoice";
  } | {
    /**
     * An approve/reject gate for a consequential action.
     *
     * @generated from field: malonaz.ai.genui.v1.Confirmation confirmation = 11;
     */
    value: ConfirmationValid;
    case: "confirmation";
  } | {
    /**
     * Structured multi-field input.
     *
     * @generated from field: malonaz.ai.genui.v1.Form form = 12;
     */
    value: FormValid;
    case: "form";
  } | {
    /**
     * Select one or more resources from candidates.
     *
     * @generated from field: malonaz.ai.genui.v1.ResourcePicker resource_picker = 13;
     */
    value: ResourcePickerValid;
    case: "resourcePicker";
  } | {
    /**
     * Bounded numeric input.
     *
     * @generated from field: malonaz.ai.genui.v1.Slider slider = 14;
     */
    value: SliderValid;
    case: "slider";
  } | {
    /**
     * A calendar/clock input.
     *
     * @generated from field: malonaz.ai.genui.v1.DateTimePicker date_time_picker = 15;
     */
    value: DateTimePickerValid;
    case: "dateTimePicker";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message malonaz.ai.genui.v1.Component.
 * Use `create(ComponentSchema)` to create a new message.
 */
export const ComponentSchema: GenMessage<Component, {validType: ComponentValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_ai_genui_v1_component, 0);

