// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file malonaz/ai/genui/v1/layout.proto (package malonaz.ai.genui.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file malonaz/ai/genui/v1/layout.proto.
 */
export const file_malonaz_ai_genui_v1_layout: GenFile = /*@__PURE__*/
  fileDesc("CiBtYWxvbmF6L2FpL2dlbnVpL3YxL2xheW91dC5wcm90bxITbWFsb25hei5haS5nZW51aS52MSJWCgRDYXJkEhUKBXRpdGxlGAEgASgJQga6SAPIAQESEAoIc3VidGl0bGUYAiABKAkSJQoNY29tcG9uZW50X2lkcxgDIAMoCUIOukgLkgEICAEiBHICEAFCLlosZ2l0aHViLmNvbS9tYWxvbmF6L2NvcmUvZ2VucHJvdG8vYWkvZ2VudWkvdjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * Groups previously emitted components under a header. Children are
 * referenced by component id rather than nested inline, so the model emits
 * leaf components first (each rendering as it streams) and then groups them
 * — and each tool's schema stays flat.
 *
 * @generated from message malonaz.ai.genui.v1.Card
 */
export type Card = Message<"malonaz.ai.genui.v1.Card"> & {
  /**
   * The header rendered at the top of the card.
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * Optional secondary line rendered under the title.
   *
   * @generated from field: string subtitle = 2;
   */
  subtitle: string;

  /**
   * Ids of previously emitted components, in render order. The client
   * re-parents them into this card.
   *
   * @generated from field: repeated string component_ids = 3;
   */
  componentIds: string[];
};

/**
 * Groups previously emitted components under a header. Children are
 * referenced by component id rather than nested inline, so the model emits
 * leaf components first (each rendering as it streams) and then groups them
 * — and each tool's schema stays flat.
 *
 * @generated from message malonaz.ai.genui.v1.Card
 */
export type CardValid = Message<"malonaz.ai.genui.v1.Card"> & {
  /**
   * The header rendered at the top of the card.
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * Optional secondary line rendered under the title.
   *
   * @generated from field: string subtitle = 2;
   */
  subtitle: string;

  /**
   * Ids of previously emitted components, in render order. The client
   * re-parents them into this card.
   *
   * @generated from field: repeated string component_ids = 3;
   */
  componentIds: string[];
};

/**
 * Describes the message malonaz.ai.genui.v1.Card.
 * Use `create(CardSchema)` to create a new message.
 */
export const CardSchema: GenMessage<Card, {validType: CardValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_ai_genui_v1_layout, 0);

