// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file malonaz/json/v1/schema.proto (package malonaz.json.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file malonaz/json/v1/schema.proto.
 */
export const file_malonaz_json_v1_schema: GenFile = /*@__PURE__*/
  fileDesc("ChxtYWxvbmF6L2pzb24vdjEvc2NoZW1hLnByb3RvEg9tYWxvbmF6Lmpzb24udjEikgYKBlNjaGVtYRJKCgR0eXBlGAEgASgJQjy6SDlyN1IGb2JqZWN0UgZzdHJpbmdSBm51bWJlclIHaW50ZWdlclIHYm9vbGVhblIFYXJyYXlSBG51bGwSEwoLZGVzY3JpcHRpb24YAiABKAkSOwoKcHJvcGVydGllcxgDIAMoCzInLm1hbG9uYXouanNvbi52MS5TY2hlbWEuUHJvcGVydGllc0VudHJ5EjYKFWFkZGl0aW9uYWxfcHJvcGVydGllcxgYIAEoCzIXLm1hbG9uYXouanNvbi52MS5TY2hlbWESEAoIcmVxdWlyZWQYBCADKAkSJgoFaXRlbXMYBSABKAsyFy5tYWxvbmF6Lmpzb24udjEuU2NoZW1hEhEKCW1pbl9pdGVtcxgGIAEoBRIRCgltYXhfaXRlbXMYByABKAUSDAoEZW51bRgIIAMoCRISCgptaW5fbGVuZ3RoGAkgASgFEhIKCm1heF9sZW5ndGgYCiABKAUSDwoHcGF0dGVybhgLIAEoCRIOCgZmb3JtYXQYDCABKAkSDwoHbWluaW11bRgNIAEoARIPCgdtYXhpbXVtGA4gASgBEhkKEWV4Y2x1c2l2ZV9taW5pbXVtGA8gASgBEhkKEWV4Y2x1c2l2ZV9tYXhpbXVtGBAgASgBEhMKC211bHRpcGxlX29mGBEgASgBEg8KB2RlZmF1bHQYEiABKAkSEAoIZXhhbXBsZXMYEyADKAkSJwoGYW55X29mGBQgAygLMhcubWFsb25hei5qc29uLnYxLlNjaGVtYRInCgZvbmVfb2YYFSADKAsyFy5tYWxvbmF6Lmpzb24udjEuU2NoZW1hEicKBmFsbF9vZhgWIAMoCzIXLm1hbG9uYXouanNvbi52MS5TY2hlbWESJAoDbm90GBcgASgLMhcubWFsb25hei5qc29uLnYxLlNjaGVtYRpKCg9Qcm9wZXJ0aWVzRW50cnkSCwoDa2V5GAEgASgJEiYKBXZhbHVlGAIgASgLMhcubWFsb25hei5qc29uLnYxLlNjaGVtYToCOAFCKlooZ2l0aHViLmNvbS9tYWxvbmF6L2NvcmUvZ2VucHJvdG8vanNvbi92MWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * Represents a JSON Schema (recursive definition)
 *
 * @generated from message malonaz.json.v1.Schema
 */
export type Schema = Message<"malonaz.json.v1.Schema"> & {
  /**
   * Specifies the data type: "object", "string", "number", "integer", "boolean", "array", "null"
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Human-readable description of what this schema represents
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * For objects
   * Defines the properties of an object type, where each property has its own schema (recursive)
   *
   * @generated from field: map<string, malonaz.json.v1.Schema> properties = 3;
   */
  properties: { [key: string]: Schema };

  /**
   * Schema for additional properties (used for map types)
   *
   * @generated from field: malonaz.json.v1.Schema additional_properties = 24;
   */
  additionalProperties?: Schema;

  /**
   * List of property names that must be present in the object
   *
   * @generated from field: repeated string required = 4;
   */
  required: string[];

  /**
   * For arrays
   * Defines the schema for elements within an array (recursive)
   *
   * @generated from field: malonaz.json.v1.Schema items = 5;
   */
  items?: Schema;

  /**
   * Minimum number of items required in the array
   *
   * @generated from field: int32 min_items = 6;
   */
  minItems: number;

  /**
   * Maximum number of items allowed in the array
   *
   * @generated from field: int32 max_items = 7;
   */
  maxItems: number;

  /**
   * For strings
   * List of allowed string values (enumeration constraint)
   *
   * @generated from field: repeated string enum = 8;
   */
  enum: string[];

  /**
   * Minimum length of the string
   *
   * @generated from field: int32 min_length = 9;
   */
  minLength: number;

  /**
   * Maximum length of the string
   *
   * @generated from field: int32 max_length = 10;
   */
  maxLength: number;

  /**
   * Regular expression pattern the string must match
   *
   * @generated from field: string pattern = 11;
   */
  pattern: string;

  /**
   * Semantic format hint: "date-time", "email", "uri", "uuid", etc.
   *
   * @generated from field: string format = 12;
   */
  format: string;

  /**
   * For numbers
   * Minimum value (inclusive) for number or integer types
   *
   * @generated from field: double minimum = 13;
   */
  minimum: number;

  /**
   * Maximum value (inclusive) for number or integer types
   *
   * @generated from field: double maximum = 14;
   */
  maximum: number;

  /**
   * Minimum value (exclusive) for number or integer types
   *
   * @generated from field: double exclusive_minimum = 15;
   */
  exclusiveMinimum: number;

  /**
   * Maximum value (exclusive) for number or integer types
   *
   * @generated from field: double exclusive_maximum = 16;
   */
  exclusiveMaximum: number;

  /**
   * The number must be a multiple of this value
   *
   * @generated from field: double multiple_of = 17;
   */
  multipleOf: number;

  /**
   * Default value to use when no value is provided
   *
   * @generated from field: string default = 18;
   */
  default: string;

  /**
   * Example values that satisfy this schema (for documentation)
   *
   * @generated from field: repeated string examples = 19;
   */
  examples: string[];

  /**
   * Advanced combinators
   * Schema is valid if it matches ANY of the provided schemas (recursive)
   *
   * @generated from field: repeated malonaz.json.v1.Schema any_of = 20;
   */
  anyOf: Schema[];

  /**
   * Schema is valid if it matches EXACTLY ONE of the provided schemas (recursive)
   *
   * @generated from field: repeated malonaz.json.v1.Schema one_of = 21;
   */
  oneOf: Schema[];

  /**
   * Schema is valid if it matches ALL of the provided schemas (recursive)
   *
   * @generated from field: repeated malonaz.json.v1.Schema all_of = 22;
   */
  allOf: Schema[];

  /**
   * Schema is valid if it does NOT match the provided schema (recursive)
   *
   * @generated from field: malonaz.json.v1.Schema not = 23;
   */
  not?: Schema;
};

export type SchemaValid = Schema;

/**
 * Describes the message malonaz.json.v1.Schema.
 * Use `create(SchemaSchema)` to create a new message.
 */
export const SchemaSchema: GenMessage<Schema, {validType: SchemaValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_json_v1_schema, 0);

