go_library(
    name = "pbutils",
    srcs = ["pbutils.go"],
    visibility = ["//..."],
    deps = [
        "//third_party/go:github.com__mennanov__fmutils",
        "//third_party/go:google.golang.org__protobuf__proto",
    ],
)
