plugin_repo(
    name = "shell",
    owner = "please-build",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "go",
    revision = "v1.18.0",
)

plugin_repo(
    name = "proto",
    owner = "malonaz",
    revision = "00f6e759abbc0aa057084cbc243d206f2de1b609",
)

plugin_repo(
    name = "core",
    owner = "malonaz",
    revision = CONFIG.CORE_REVISION,
)
