go_module(
    name = "go-bindata",
    binary = True,
    download = "//third_party/go:_github.com__kevinburke__go-bindata__v4#download",
    install = ["go-bindata"],
    module = "github.com/kevinburke/go-bindata",
    visibility = ["PUBLIC"],
    deps = [],
)
