go_library(
    name = "context_utils",
    srcs = ["context_utils.go"],
    visibility = ["//..."],
    deps = [
        "//third_party/go:golang.org__x__net__context",
        "//third_party/go:google.golang.org__grpc__metadata",
    ],
)
