go_library(
    name = "require",
    srcs = ["errors.go"],
    test_only = True,
    visibility = ["//core/..."],
    deps = [
        "//third_party/go:github.com__stretchr__testify__require",
        "//third_party/go:google.golang.org__grpc__codes",
        "//third_party/go:google.golang.org__grpc__status",
    ],
)
