go_library(
    name = "require",
    srcs = ["require.go"],
    test_only = True,
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:github.com__google__go-cmp__cmp",
        "//third_party/go:github.com__stretchr__testify__require",
        "//third_party/go:google.golang.org__grpc__codes",
        "//third_party/go:google.golang.org__grpc__status",
        "//third_party/go:google.golang.org__protobuf__proto",
        "//third_party/go:google.golang.org__protobuf__testing__protocmp",
    ],
)
