go_library(
    name = "aip",
    srcs = ["aip.go"],
    visibility = ["//..."],
    deps = [
        "//go/logging",
        "//third_party/go:github.com__pkg__errors",
        "//third_party/go:go.einride.tech__aip__filtering",
        "//third_party/go:go.einride.tech__aip__ordering",
        "//third_party/go:go.einride.tech__aip__pagination",
        "//third_party/go:go.einride.tech__spanner-aip__spanfiltering",
        "//third_party/go:go.einride.tech__spanner-aip__spanordering",
        "//third_party/go:google.golang.org__protobuf__proto",
    ],
)
