go_binary(
    name = "grafana-upload-dashboard",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//go/flags",
        "//go/grafana",
        "//third_party/go:github.com__grafana__grafana-openapi-client-go__models",
    ],
)
