go_library(
    name = "operation",
    srcs = ["operation.go"],
    visibility = ["//..."],
    deps = [
        "//go/logging",
        "//go/operation/proto:api",
        "//third_party/go:github.com__pkg__errors",
        "//third_party/go:google.golang.org__genproto__googleapis__longrunning",
        "//third_party/go:google.golang.org__genproto__googleapis__rpc__status",
        "//third_party/go:google.golang.org__grpc__codes",
        "//third_party/go:google.golang.org__grpc__status",
        "//third_party/go:google.golang.org__protobuf__proto",
        "//third_party/go:google.golang.org__protobuf__types__known__anypb",
        "//third_party/go:google.golang.org__protobuf__types__known__emptypb",
    ],
)
