package(default_visibility = ["PUBLIC"])

export_file(
    name = "docker",
    src = "docker.build_defs",
)

export_file(
    name = "grafana",
    src = "grafana.build_defs",
)

export_file(
    name = "k8s",
    src = "k8s.build_defs",
)

export_file(
    name = "go_bindata",
    src = "go_bindata.build_defs",
)

export_file(
    name = "remote",
    src = "remote.build_defs",
)

export_file(
    name = "crown_package",
    src = "crown_package.build_defs",
)

export_file(
    name = "proto_extensions",
    src = "proto_extensions.build_defs",
)

export_file(
    name = "fpm",
    src = "fpm.build_defs",
)

export_file(
    name = "distroless",
    src = "distroless.build_defs",
)

export_file(
    name = "utils",
    src = "utils.build_defs",
)

export_file(
    name = "template",
    src = "template.build_defs",
)
