proto_library(
    name = "resource_annotations",
    srcs = ["resource_annotations.proto"],
    additional_context = {
        GO_IMPORT_PATH: "github.com/malonaz/core/genproto/test/resource_annotations/v1",
        GENERATE_GO_AIP: True,
    },
    test_only = True,
    deps = [
        "//third_party/proto:google__api__annotations",
    ],
)
