proto_library(
    name = "resource_annotations",
    srcs = ["resource_annotations.proto"],
    additional_context = {
        GENERATE_GO_AIP: True,
    },
    test_only = True,
    deps = [
        "//third_party/proto:googleapis_annotations",
    ],
)
