filegroup(
    name = "certs",
    srcs = [
        "ca.crt",
        "client.crt",
        "client.key",
        "server.crt",
        "server.key",
    ],
    visibility = ["//common/docker_containers/..."],
)
