---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grafana
  namespace: monitoring
spec:
  healthCheck:
    requestPath: /api/health
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap
