// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: malonaz/codegen/model/v1/model.proto

//go:build protoopaque

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelOpts defines code generation options for an entire message/model.
// Controls database mapping and which CRUD functions are generated.
type ModelOpts struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SchemaName   string                 `protobuf:"bytes,1,opt,name=schema_name,json=schemaName,proto3"`
	xxx_hidden_TableName    string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3"`
	xxx_hidden_IdColumnName string                 `protobuf:"bytes,3,opt,name=id_column_name,json=idColumnName,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ModelOpts) Reset() {
	*x = ModelOpts{}
	mi := &file_malonaz_codegen_model_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelOpts) ProtoMessage() {}

func (x *ModelOpts) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_codegen_model_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelOpts) GetSchemaName() string {
	if x != nil {
		return x.xxx_hidden_SchemaName
	}
	return ""
}

func (x *ModelOpts) GetTableName() string {
	if x != nil {
		return x.xxx_hidden_TableName
	}
	return ""
}

func (x *ModelOpts) GetIdColumnName() string {
	if x != nil {
		return x.xxx_hidden_IdColumnName
	}
	return ""
}

func (x *ModelOpts) SetSchemaName(v string) {
	x.xxx_hidden_SchemaName = v
}

func (x *ModelOpts) SetTableName(v string) {
	x.xxx_hidden_TableName = v
}

func (x *ModelOpts) SetIdColumnName(v string) {
	x.xxx_hidden_IdColumnName = v
}

type ModelOpts_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Set a schema. Defaults to 'public'.
	SchemaName string
	// Override the default table name for this model.
	// If not set, uses a default derived from the message name.
	TableName string
	// Override the id column name. Cannot be set for singletons as they have no id.
	IdColumnName string
}

func (b0 ModelOpts_builder) Build() *ModelOpts {
	m0 := &ModelOpts{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SchemaName = b.SchemaName
	x.xxx_hidden_TableName = b.TableName
	x.xxx_hidden_IdColumnName = b.IdColumnName
	return m0
}

// FieldOpts defines code generation options for individual message fields.
// Controls serialization format and nullability handling.
type FieldOpts struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ColumnName   string                 `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3"`
	xxx_hidden_AsJsonBytes  bool                   `protobuf:"varint,2,opt,name=as_json_bytes,json=asJsonBytes,proto3"`
	xxx_hidden_AsProtoBytes bool                   `protobuf:"varint,3,opt,name=as_proto_bytes,json=asProtoBytes,proto3"`
	xxx_hidden_Nullable     bool                   `protobuf:"varint,4,opt,name=nullable,proto3"`
	xxx_hidden_Skip         bool                   `protobuf:"varint,5,opt,name=skip,proto3"`
	xxx_hidden_Embed        bool                   `protobuf:"varint,6,opt,name=embed,proto3"`
	xxx_hidden_PgVector     bool                   `protobuf:"varint,7,opt,name=pg_vector,json=pgVector,proto3"`
	xxx_hidden_Join         *Join                  `protobuf:"bytes,8,opt,name=join,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FieldOpts) Reset() {
	*x = FieldOpts{}
	mi := &file_malonaz_codegen_model_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOpts) ProtoMessage() {}

func (x *FieldOpts) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_codegen_model_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOpts) GetColumnName() string {
	if x != nil {
		return x.xxx_hidden_ColumnName
	}
	return ""
}

func (x *FieldOpts) GetAsJsonBytes() bool {
	if x != nil {
		return x.xxx_hidden_AsJsonBytes
	}
	return false
}

func (x *FieldOpts) GetAsProtoBytes() bool {
	if x != nil {
		return x.xxx_hidden_AsProtoBytes
	}
	return false
}

func (x *FieldOpts) GetNullable() bool {
	if x != nil {
		return x.xxx_hidden_Nullable
	}
	return false
}

func (x *FieldOpts) GetSkip() bool {
	if x != nil {
		return x.xxx_hidden_Skip
	}
	return false
}

func (x *FieldOpts) GetEmbed() bool {
	if x != nil {
		return x.xxx_hidden_Embed
	}
	return false
}

func (x *FieldOpts) GetPgVector() bool {
	if x != nil {
		return x.xxx_hidden_PgVector
	}
	return false
}

func (x *FieldOpts) GetJoin() *Join {
	if x != nil {
		return x.xxx_hidden_Join
	}
	return nil
}

func (x *FieldOpts) SetColumnName(v string) {
	x.xxx_hidden_ColumnName = v
}

func (x *FieldOpts) SetAsJsonBytes(v bool) {
	x.xxx_hidden_AsJsonBytes = v
}

func (x *FieldOpts) SetAsProtoBytes(v bool) {
	x.xxx_hidden_AsProtoBytes = v
}

func (x *FieldOpts) SetNullable(v bool) {
	x.xxx_hidden_Nullable = v
}

func (x *FieldOpts) SetSkip(v bool) {
	x.xxx_hidden_Skip = v
}

func (x *FieldOpts) SetEmbed(v bool) {
	x.xxx_hidden_Embed = v
}

func (x *FieldOpts) SetPgVector(v bool) {
	x.xxx_hidden_PgVector = v
}

func (x *FieldOpts) SetJoin(v *Join) {
	x.xxx_hidden_Join = v
}

func (x *FieldOpts) HasJoin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Join != nil
}

func (x *FieldOpts) ClearJoin() {
	x.xxx_hidden_Join = nil
}

type FieldOpts_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Override the column name for this field.
	ColumnName string
	// If true, serialize this field as JSON bytes in the database.
	// The field will be stored as JSONB and marshaled/unmarshaled using JSON encoding.
	AsJsonBytes bool
	// If true, serialize this field as Protocol Buffer bytes in the database.
	// The field will be stored as bytea and marshaled/unmarshaled using protobuf encoding.
	AsProtoBytes bool
	// If true, treat this field as nullable (use pointer type in Go).
	// Allows distinguishing between zero values and null/unset values.
	Nullable bool
	// If true, skip this field entirely in code generation.
	// The field will not be included in database models or conversion functions.
	Skip bool
	// If true, embed this field's properties directly into the parent struct.
	// Instead of a nested field, the properties are flattened into the parent.
	Embed bool
	// If true, treat this field as a pgvector type for vector similarity search.
	// The field will use the pgvector.Vector type for PostgreSQL vector operations.
	PgVector bool
	// If set, this field is populated via a JOIN and is output-only.
	Join *Join
}

func (b0 FieldOpts_builder) Build() *FieldOpts {
	m0 := &FieldOpts{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ColumnName = b.ColumnName
	x.xxx_hidden_AsJsonBytes = b.AsJsonBytes
	x.xxx_hidden_AsProtoBytes = b.AsProtoBytes
	x.xxx_hidden_Nullable = b.Nullable
	x.xxx_hidden_Skip = b.Skip
	x.xxx_hidden_Embed = b.Embed
	x.xxx_hidden_PgVector = b.PgVector
	x.xxx_hidden_Join = b.Join
	return m0
}

// Configures a field that is populated via a JOIN.
type Join struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source isJoin_Source          `protobuf_oneof:"source"`
	xxx_hidden_Field  string                 `protobuf:"bytes,2,opt,name=field,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_malonaz_codegen_model_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_codegen_model_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Join) GetParent() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*join_Parent); ok {
			return x.Parent
		}
	}
	return ""
}

func (x *Join) GetReference() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*join_Reference); ok {
			return x.Reference
		}
	}
	return ""
}

func (x *Join) GetField() string {
	if x != nil {
		return x.xxx_hidden_Field
	}
	return ""
}

func (x *Join) SetParent(v string) {
	x.xxx_hidden_Source = &join_Parent{v}
}

func (x *Join) SetReference(v string) {
	x.xxx_hidden_Source = &join_Reference{v}
}

func (x *Join) SetField(v string) {
	x.xxx_hidden_Field = v
}

func (x *Join) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Join) HasParent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*join_Parent)
	return ok
}

func (x *Join) HasReference() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*join_Reference)
	return ok
}

func (x *Join) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *Join) ClearParent() {
	if _, ok := x.xxx_hidden_Source.(*join_Parent); ok {
		x.xxx_hidden_Source = nil
	}
}

func (x *Join) ClearReference() {
	if _, ok := x.xxx_hidden_Source.(*join_Reference); ok {
		x.xxx_hidden_Source = nil
	}
}

const Join_Source_not_set_case case_Join_Source = 0
const Join_Parent_case case_Join_Source = 1
const Join_Reference_case case_Join_Source = 3

func (x *Join) WhichSource() case_Join_Source {
	if x == nil {
		return Join_Source_not_set_case
	}
	switch x.xxx_hidden_Source.(type) {
	case *join_Parent:
		return Join_Parent_case
	case *join_Reference:
		return Join_Reference_case
	default:
		return Join_Source_not_set_case
	}
}

type Join_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. The source of the join.

	// Fields of oneof xxx_hidden_Source:
	// The parent resource type to join on. The join conditions equate the
	// parent's identifier columns with this resource's foreign key columns.
	Parent *string
	// The name of a field on *this* message holding a resource name
	// reference (annotated with google.api.resource_reference). The
	// referenced resource's type is resolved from that annotation. The join
	// conditions equate the shared identifier columns and extract the final
	// identifier from the stored name.
	Reference *string
	// -- end of xxx_hidden_Source
	// Required. The field name on the joined message to populate from.
	Field string
}

func (b0 Join_builder) Build() *Join {
	m0 := &Join{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Parent != nil {
		x.xxx_hidden_Source = &join_Parent{*b.Parent}
	}
	if b.Reference != nil {
		x.xxx_hidden_Source = &join_Reference{*b.Reference}
	}
	x.xxx_hidden_Field = b.Field
	return m0
}

type case_Join_Source protoreflect.FieldNumber

func (x case_Join_Source) String() string {
	md := file_malonaz_codegen_model_v1_model_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isJoin_Source interface {
	isJoin_Source()
}

type join_Parent struct {
	// The parent resource type to join on. The join conditions equate the
	// parent's identifier columns with this resource's foreign key columns.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3,oneof"`
}

type join_Reference struct {
	// The name of a field on *this* message holding a resource name
	// reference (annotated with google.api.resource_reference). The
	// referenced resource's type is resolved from that annotation. The join
	// conditions equate the shared identifier columns and extract the final
	// identifier from the stored name.
	Reference string `protobuf:"bytes,3,opt,name=reference,proto3,oneof"`
}

func (*join_Parent) isJoin_Source() {}

func (*join_Reference) isJoin_Source() {}

var file_malonaz_codegen_model_v1_model_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ModelOpts)(nil),
		Field:         8810,
		Name:          "malonaz.codegen.model.v1.model_opts",
		Tag:           "bytes,8810,opt,name=model_opts",
		Filename:      "malonaz/codegen/model/v1/model.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOpts)(nil),
		Field:         32423,
		Name:          "malonaz.codegen.model.v1.field_opts",
		Tag:           "bytes,32423,opt,name=field_opts",
		Filename:      "malonaz/codegen/model/v1/model.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Opts for a model.
	//
	// optional malonaz.codegen.model.v1.ModelOpts model_opts = 8810;
	E_ModelOpts = &file_malonaz_codegen_model_v1_model_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Opts for a field.
	//
	// optional malonaz.codegen.model.v1.FieldOpts field_opts = 32423;
	E_FieldOpts = &file_malonaz_codegen_model_v1_model_proto_extTypes[1]
)

var File_malonaz_codegen_model_v1_model_proto protoreflect.FileDescriptor

const file_malonaz_codegen_model_v1_model_proto_rawDesc = "" +
	"\n" +
	"$malonaz/codegen/model/v1/model.proto\x12\x18malonaz.codegen.model.v1\x1a\x19google/api/resource.proto\x1a google/protobuf/descriptor.proto\"q\n" +
	"\tModelOpts\x12\x1f\n" +
	"\vschema_name\x18\x01 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12$\n" +
	"\x0eid_column_name\x18\x03 \x01(\tR\fidColumnName\"\x8d\x02\n" +
	"\tFieldOpts\x12\x1f\n" +
	"\vcolumn_name\x18\x01 \x01(\tR\n" +
	"columnName\x12\"\n" +
	"\ras_json_bytes\x18\x02 \x01(\bR\vasJsonBytes\x12$\n" +
	"\x0eas_proto_bytes\x18\x03 \x01(\bR\fasProtoBytes\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\bR\x04skip\x12\x14\n" +
	"\x05embed\x18\x06 \x01(\bR\x05embed\x12\x1b\n" +
	"\tpg_vector\x18\a \x01(\bR\bpgVector\x122\n" +
	"\x04join\x18\b \x01(\v2\x1e.malonaz.codegen.model.v1.JoinR\x04join\"h\n" +
	"\x04Join\x12 \n" +
	"\x06parent\x18\x01 \x01(\tB\x06\xfaA\x03\n" +
	"\x01*H\x00R\x06parent\x12\x1e\n" +
	"\treference\x18\x03 \x01(\tH\x00R\treference\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05fieldB\b\n" +
	"\x06source:d\n" +
	"\n" +
	"model_opts\x12\x1f.google.protobuf.MessageOptions\x18\xeaD \x01(\v2#.malonaz.codegen.model.v1.ModelOptsR\tmodelOpts:c\n" +
	"\n" +
	"field_opts\x12\x1d.google.protobuf.FieldOptions\x18\xa7\xfd\x01 \x01(\v2#.malonaz.codegen.model.v1.FieldOptsR\tfieldOptsB3Z1github.com/malonaz/core/genproto/codegen/model/v1b\x06proto3"

var file_malonaz_codegen_model_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_malonaz_codegen_model_v1_model_proto_goTypes = []any{
	(*ModelOpts)(nil),                   // 0: malonaz.codegen.model.v1.ModelOpts
	(*FieldOpts)(nil),                   // 1: malonaz.codegen.model.v1.FieldOpts
	(*Join)(nil),                        // 2: malonaz.codegen.model.v1.Join
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_malonaz_codegen_model_v1_model_proto_depIdxs = []int32{
	2, // 0: malonaz.codegen.model.v1.FieldOpts.join:type_name -> malonaz.codegen.model.v1.Join
	3, // 1: malonaz.codegen.model.v1.model_opts:extendee -> google.protobuf.MessageOptions
	4, // 2: malonaz.codegen.model.v1.field_opts:extendee -> google.protobuf.FieldOptions
	0, // 3: malonaz.codegen.model.v1.model_opts:type_name -> malonaz.codegen.model.v1.ModelOpts
	1, // 4: malonaz.codegen.model.v1.field_opts:type_name -> malonaz.codegen.model.v1.FieldOpts
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_malonaz_codegen_model_v1_model_proto_init() }
func file_malonaz_codegen_model_v1_model_proto_init() {
	if File_malonaz_codegen_model_v1_model_proto != nil {
		return
	}
	file_malonaz_codegen_model_v1_model_proto_msgTypes[2].OneofWrappers = []any{
		(*join_Parent)(nil),
		(*join_Reference)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malonaz_codegen_model_v1_model_proto_rawDesc), len(file_malonaz_codegen_model_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_malonaz_codegen_model_v1_model_proto_goTypes,
		DependencyIndexes: file_malonaz_codegen_model_v1_model_proto_depIdxs,
		MessageInfos:      file_malonaz_codegen_model_v1_model_proto_msgTypes,
		ExtensionInfos:    file_malonaz_codegen_model_v1_model_proto_extTypes,
	}.Build()
	File_malonaz_codegen_model_v1_model_proto = out.File
	file_malonaz_codegen_model_v1_model_proto_goTypes = nil
	file_malonaz_codegen_model_v1_model_proto_depIdxs = nil
}
