go_library(
    name = "prometheus",
    srcs = ["opts.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//go/logging",
        "//third_party/go:github.com__prometheus__client_golang__prometheus__promhttp",
    ],
)
