go_library(
    name = "migrator",
    srcs = [
        "migrator.go",
        "sql_queries.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//go/logging",
        "//go/postgres",
        "//go/postgres/migrator/migrations",
    ],
)
