subinclude("//build_defs/codegen/postgres:build_defs")

postgres_migrations(
    name = "migrations",
    dirs = [
        "job",
        "queue",
        "schema",
        "target",
    ],
    visibility = ["PUBLIC"],
)
