go_library(
    name = "schema",
    srcs = ["schema.go"],
    visibility = ["//..."],
    deps = [
        "//go/pbutil",
        "//malonaz/codegen/model/v1",
        "//third_party/go:github.com__huandu__xstrings",
        "//third_party/go:google.golang.org__protobuf__compiler__protogen",
        "//tools/protoc-gen-core/resource",
    ],
)
