package(default_visibility = ["PUBLIC"])

export_file(
    name = "main.go.tmpl",
    src = "main.go.tmpl",
)

export_file(
    name = "main.opts.go.tmpl",
    src = "main.opts.go.tmpl",
)

export_file(
    name = "main.shutdown.go.tmpl",
    src = "main.shutdown.go.tmpl",
)
