proto_library(
    name = "aip",
    srcs = ["aip.proto"],
    test_only = True,
    visibility = ["//go/aip/..."],
    deps = [
        "//genproto/codegen/aip/v1",
        "//proto/codegen/aip/v1",
    ],
)
