proto_library(
    name = "aip",
    srcs = ["aip.proto"],
    test_only = True,
    visibility = ["//go/aip/..."],
    deps = [
        "//third_party/proto:core__codegen__aip__v1",
        "//third_party/proto:google__api__expr__v1alpha1",
    ],
)
