// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: malonaz/onyx/v1/main.proto

//go:build protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A gRPC server interceptor.
type Interceptor int32

const (
	// Used to detect an unset field.
	Interceptor_INTERCEPTOR_UNSPECIFIED Interceptor = 0
	// Gives the session manager a local context for the request.
	Interceptor_INTERCEPTOR_SESSION_LOCAL_CONTEXT_INJECTOR Interceptor = 1
	// Authenticates external callers by API key.
	Interceptor_INTERCEPTOR_EXTERNAL_API_KEY_AUTHENTICATION Interceptor = 2
	// Authenticates internal services by shared secret.
	Interceptor_INTERCEPTOR_INTERNAL_SERVICE_AUTHENTICATION Interceptor = 3
	// Authenticates callers by JWT.
	Interceptor_INTERCEPTOR_JWT_AUTHENTICATION Interceptor = 4
	// Authorizes the authenticated session against the method's permissions.
	Interceptor_INTERCEPTOR_PERMISSION_AUTHENTICATION Interceptor = 5
	// Adds the session to the request log fields.
	Interceptor_INTERCEPTOR_SESSION_LOG_INJECTOR Interceptor = 6
	// Propagates the session on outgoing calls.
	Interceptor_INTERCEPTOR_SESSION_OUTGOING_CONTEXT_INJECTOR Interceptor = 7
)

// Enum value maps for Interceptor.
var (
	Interceptor_name = map[int32]string{
		0: "INTERCEPTOR_UNSPECIFIED",
		1: "INTERCEPTOR_SESSION_LOCAL_CONTEXT_INJECTOR",
		2: "INTERCEPTOR_EXTERNAL_API_KEY_AUTHENTICATION",
		3: "INTERCEPTOR_INTERNAL_SERVICE_AUTHENTICATION",
		4: "INTERCEPTOR_JWT_AUTHENTICATION",
		5: "INTERCEPTOR_PERMISSION_AUTHENTICATION",
		6: "INTERCEPTOR_SESSION_LOG_INJECTOR",
		7: "INTERCEPTOR_SESSION_OUTGOING_CONTEXT_INJECTOR",
	}
	Interceptor_value = map[string]int32{
		"INTERCEPTOR_UNSPECIFIED":                       0,
		"INTERCEPTOR_SESSION_LOCAL_CONTEXT_INJECTOR":    1,
		"INTERCEPTOR_EXTERNAL_API_KEY_AUTHENTICATION":   2,
		"INTERCEPTOR_INTERNAL_SERVICE_AUTHENTICATION":   3,
		"INTERCEPTOR_JWT_AUTHENTICATION":                4,
		"INTERCEPTOR_PERMISSION_AUTHENTICATION":         5,
		"INTERCEPTOR_SESSION_LOG_INJECTOR":              6,
		"INTERCEPTOR_SESSION_OUTGOING_CONTEXT_INJECTOR": 7,
	}
)

func (x Interceptor) Enum() *Interceptor {
	p := new(Interceptor)
	*p = x
	return p
}

func (x Interceptor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interceptor) Descriptor() protoreflect.EnumDescriptor {
	return file_malonaz_onyx_v1_main_proto_enumTypes[0].Descriptor()
}

func (Interceptor) Type() protoreflect.EnumType {
	return &file_malonaz_onyx_v1_main_proto_enumTypes[0]
}

func (x Interceptor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A Go binary: the servers composing services, and the flags and wiring generated for them.
type MainManifest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name    string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Setup   bool                   `protobuf:"varint,2,opt,name=setup,proto3"`
	xxx_hidden_Servers *[]*Server             `protobuf:"bytes,3,rep,name=servers,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MainManifest) Reset() {
	*x = MainManifest{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainManifest) ProtoMessage() {}

func (x *MainManifest) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MainManifest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *MainManifest) GetSetup() bool {
	if x != nil {
		return x.xxx_hidden_Setup
	}
	return false
}

func (x *MainManifest) GetServers() []*Server {
	if x != nil {
		if x.xxx_hidden_Servers != nil {
			return *x.xxx_hidden_Servers
		}
	}
	return nil
}

func (x *MainManifest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *MainManifest) SetSetup(v bool) {
	x.xxx_hidden_Setup = v
}

func (x *MainManifest) SetServers(v []*Server) {
	x.xxx_hidden_Servers = &v
}

type MainManifest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Kebab-case name of the binary.
	Name string
	// The package defines `setup(ctx) error`, run before anything starts (e.g. migrations).
	Setup bool
	// Started in dependency order: a server after every server it dials in-process.
	Servers []*Server
}

func (b0 MainManifest_builder) Build() *MainManifest {
	m0 := &MainManifest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Setup = b.Setup
	x.xxx_hidden_Servers = &b.Servers
	return m0
}

// A server of the binary.
type Server struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Kind isServer_Kind          `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Server) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Server) GetGrpc() *Server_Grpc {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*server_Grpc_); ok {
			return x.Grpc
		}
	}
	return nil
}

func (x *Server) GetHttp() *Server_Http {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*server_Http_); ok {
			return x.Http
		}
	}
	return nil
}

func (x *Server) GetGrpcWebProxy() *Server_GrpcWebProxy {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*server_GrpcWebProxy_); ok {
			return x.GrpcWebProxy
		}
	}
	return nil
}

func (x *Server) GetProcessor() *Server_Processor {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*server_Processor_); ok {
			return x.Processor
		}
	}
	return nil
}

func (x *Server) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Server) SetGrpc(v *Server_Grpc) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &server_Grpc_{v}
}

func (x *Server) SetHttp(v *Server_Http) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &server_Http_{v}
}

func (x *Server) SetGrpcWebProxy(v *Server_GrpcWebProxy) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &server_GrpcWebProxy_{v}
}

func (x *Server) SetProcessor(v *Server_Processor) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &server_Processor_{v}
}

func (x *Server) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Server) HasGrpc() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*server_Grpc_)
	return ok
}

func (x *Server) HasHttp() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*server_Http_)
	return ok
}

func (x *Server) HasGrpcWebProxy() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*server_GrpcWebProxy_)
	return ok
}

func (x *Server) HasProcessor() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*server_Processor_)
	return ok
}

func (x *Server) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Server) ClearGrpc() {
	if _, ok := x.xxx_hidden_Kind.(*server_Grpc_); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Server) ClearHttp() {
	if _, ok := x.xxx_hidden_Kind.(*server_Http_); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Server) ClearGrpcWebProxy() {
	if _, ok := x.xxx_hidden_Kind.(*server_GrpcWebProxy_); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Server) ClearProcessor() {
	if _, ok := x.xxx_hidden_Kind.(*server_Processor_); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Server_Kind_not_set_case case_Server_Kind = 0
const Server_Grpc_case case_Server_Kind = 2
const Server_Http_case case_Server_Kind = 3
const Server_GrpcWebProxy_case case_Server_Kind = 4
const Server_Processor_case case_Server_Kind = 5

func (x *Server) WhichKind() case_Server_Kind {
	if x == nil {
		return Server_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *server_Grpc_:
		return Server_Grpc_case
	case *server_Http_:
		return Server_Http_case
	case *server_GrpcWebProxy_:
		return Server_GrpcWebProxy_case
	case *server_Processor_:
		return Server_Processor_case
	default:
		return Server_Kind_not_set_case
	}
}

type Server_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Kebab-case. The flag namespace (`{name}-grpc`, `{name}-http`, ...) and health entry of the server.
	// A gRPC server named after the one service it serves shares that service's flags.
	Name string
	// Which kind.

	// Fields of oneof xxx_hidden_Kind:
	// A gRPC server.
	Grpc *Server_Grpc
	// An HTTP server.
	Http *Server_Http
	// A grpc-web to gRPC proxy.
	GrpcWebProxy *Server_GrpcWebProxy
	// A service with no listener.
	Processor *Server_Processor
	// -- end of xxx_hidden_Kind
}

func (b0 Server_builder) Build() *Server {
	m0 := &Server{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	if b.Grpc != nil {
		x.xxx_hidden_Kind = &server_Grpc_{b.Grpc}
	}
	if b.Http != nil {
		x.xxx_hidden_Kind = &server_Http_{b.Http}
	}
	if b.GrpcWebProxy != nil {
		x.xxx_hidden_Kind = &server_GrpcWebProxy_{b.GrpcWebProxy}
	}
	if b.Processor != nil {
		x.xxx_hidden_Kind = &server_Processor_{b.Processor}
	}
	return m0
}

type case_Server_Kind protoreflect.FieldNumber

func (x case_Server_Kind) String() string {
	md := file_malonaz_onyx_v1_main_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isServer_Kind interface {
	isServer_Kind()
}

type server_Grpc_ struct {
	// A gRPC server.
	Grpc *Server_Grpc `protobuf:"bytes,2,opt,name=grpc,proto3,oneof"`
}

type server_Http_ struct {
	// An HTTP server.
	Http *Server_Http `protobuf:"bytes,3,opt,name=http,proto3,oneof"`
}

type server_GrpcWebProxy_ struct {
	// A grpc-web to gRPC proxy.
	GrpcWebProxy *Server_GrpcWebProxy `protobuf:"bytes,4,opt,name=grpc_web_proxy,json=grpcWebProxy,proto3,oneof"`
}

type server_Processor_ struct {
	// A service with no listener.
	Processor *Server_Processor `protobuf:"bytes,5,opt,name=processor,proto3,oneof"`
}

func (*server_Grpc_) isServer_Kind() {}

func (*server_Http_) isServer_Kind() {}

func (*server_GrpcWebProxy_) isServer_Kind() {}

func (*server_Processor_) isServer_Kind() {}

// A gRPC server.
type Server_Grpc struct {
	state                    protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Interceptors  []Interceptor           `protobuf:"varint,1,rep,packed,name=interceptors,proto3,enum=malonaz.onyx.v1.Interceptor"`
	xxx_hidden_DescriptorSet string                  `protobuf:"bytes,2,opt,name=descriptor_set,json=descriptorSet,proto3"`
	xxx_hidden_Services      *[]*Server_Grpc_Service `protobuf:"bytes,3,rep,name=services,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Server_Grpc) Reset() {
	*x = Server_Grpc{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Grpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Grpc) ProtoMessage() {}

func (x *Server_Grpc) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Server_Grpc) GetInterceptors() []Interceptor {
	if x != nil {
		return x.xxx_hidden_Interceptors
	}
	return nil
}

func (x *Server_Grpc) GetDescriptorSet() string {
	if x != nil {
		return x.xxx_hidden_DescriptorSet
	}
	return ""
}

func (x *Server_Grpc) GetServices() []*Server_Grpc_Service {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *Server_Grpc) SetInterceptors(v []Interceptor) {
	x.xxx_hidden_Interceptors = v
}

func (x *Server_Grpc) SetDescriptorSet(v string) {
	x.xxx_hidden_DescriptorSet = v
}

func (x *Server_Grpc) SetServices(v []*Server_Grpc_Service) {
	x.xxx_hidden_Services = &v
}

type Server_Grpc_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Outermost first.
	Interceptors []Interceptor
	// Path, relative to the main package, of a FileDescriptorSet to embed for reflection.
	DescriptorSet string
	// Services registered on this server.
	Services []*Server_Grpc_Service
}

func (b0 Server_Grpc_builder) Build() *Server_Grpc {
	m0 := &Server_Grpc{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interceptors = b.Interceptors
	x.xxx_hidden_DescriptorSet = b.DescriptorSet
	x.xxx_hidden_Services = &b.Services
	return m0
}

// An HTTP server.
type Server_Http struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Services *[]*Server_Http_Service `protobuf:"bytes,1,rep,name=services,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Server_Http) Reset() {
	*x = Server_Http{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Http) ProtoMessage() {}

func (x *Server_Http) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Server_Http) GetServices() []*Server_Http_Service {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *Server_Http) SetServices(v []*Server_Http_Service) {
	x.xxx_hidden_Services = &v
}

type Server_Http_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Services registering routes on this server.
	Services []*Server_Http_Service
}

func (b0 Server_Http_builder) Build() *Server_Http {
	m0 := &Server_Http{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Services = &b.Services
	return m0
}

// A grpc-web to gRPC proxy; the backend is configured by its own flags.
type Server_GrpcWebProxy struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GrpcWebProxy) Reset() {
	*x = Server_GrpcWebProxy{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GrpcWebProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GrpcWebProxy) ProtoMessage() {}

func (x *Server_GrpcWebProxy) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Server_GrpcWebProxy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Server_GrpcWebProxy_builder) Build() *Server_GrpcWebProxy {
	m0 := &Server_GrpcWebProxy{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// A service with no listener: started and health-checked, nothing more.
type Server_Processor struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Manifest string                 `protobuf:"bytes,1,opt,name=manifest,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Server_Processor) Reset() {
	*x = Server_Processor{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Processor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Processor) ProtoMessage() {}

func (x *Server_Processor) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Server_Processor) GetManifest() string {
	if x != nil {
		return x.xxx_hidden_Manifest
	}
	return ""
}

func (x *Server_Processor) SetManifest(v string) {
	x.xxx_hidden_Manifest = v
}

type Server_Processor_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Please label of the ServiceManifest.
	Manifest string
}

func (b0 Server_Processor_builder) Build() *Server_Processor {
	m0 := &Server_Processor{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Manifest = b.Manifest
	return m0
}

// A gRPC service registered on the server.
type Server_Grpc_Service struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Proto    string                 `protobuf:"bytes,1,opt,name=proto,proto3"`
	xxx_hidden_Service  string                 `protobuf:"bytes,2,opt,name=service,proto3"`
	xxx_hidden_Manifest string                 `protobuf:"bytes,3,opt,name=manifest,proto3"`
	xxx_hidden_Gateway  bool                   `protobuf:"varint,4,opt,name=gateway,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Server_Grpc_Service) Reset() {
	*x = Server_Grpc_Service{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Grpc_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Grpc_Service) ProtoMessage() {}

func (x *Server_Grpc_Service) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Server_Grpc_Service) GetProto() string {
	if x != nil {
		return x.xxx_hidden_Proto
	}
	return ""
}

func (x *Server_Grpc_Service) GetService() string {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return ""
}

func (x *Server_Grpc_Service) GetManifest() string {
	if x != nil {
		return x.xxx_hidden_Manifest
	}
	return ""
}

func (x *Server_Grpc_Service) GetGateway() bool {
	if x != nil {
		return x.xxx_hidden_Gateway
	}
	return false
}

func (x *Server_Grpc_Service) SetProto(v string) {
	x.xxx_hidden_Proto = v
}

func (x *Server_Grpc_Service) SetService(v string) {
	x.xxx_hidden_Service = v
}

func (x *Server_Grpc_Service) SetManifest(v string) {
	x.xxx_hidden_Manifest = v
}

func (x *Server_Grpc_Service) SetGateway(v bool) {
	x.xxx_hidden_Gateway = v
}

type Server_Grpc_Service_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Please label of the proto library declaring the service.
	Proto string
	// Kebab-case name of the proto service.
	Service string
	// Please label of the ServiceManifest implementing it.
	Manifest string
	// Also serve it over HTTP through grpc-gateway.
	Gateway bool
}

func (b0 Server_Grpc_Service_builder) Build() *Server_Grpc_Service {
	m0 := &Server_Grpc_Service{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Proto = b.Proto
	x.xxx_hidden_Service = b.Service
	x.xxx_hidden_Manifest = b.Manifest
	x.xxx_hidden_Gateway = b.Gateway
	return m0
}

// A service registering routes on the server.
type Server_Http_Service struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Manifest string                 `protobuf:"bytes,1,opt,name=manifest,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Server_Http_Service) Reset() {
	*x = Server_Http_Service{}
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Http_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Http_Service) ProtoMessage() {}

func (x *Server_Http_Service) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_onyx_v1_main_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Server_Http_Service) GetManifest() string {
	if x != nil {
		return x.xxx_hidden_Manifest
	}
	return ""
}

func (x *Server_Http_Service) SetManifest(v string) {
	x.xxx_hidden_Manifest = v
}

type Server_Http_Service_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Please label of the ServiceManifest; its Service must implement RegisterRoutes.
	Manifest string
}

func (b0 Server_Http_Service_builder) Build() *Server_Http_Service {
	m0 := &Server_Http_Service{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Manifest = b.Manifest
	return m0
}

var File_malonaz_onyx_v1_main_proto protoreflect.FileDescriptor

const file_malonaz_onyx_v1_main_proto_rawDesc = "" +
	"\n" +
	"\x1amalonaz/onyx/v1/main.proto\x12\x0fmalonaz.onyx.v1\x1a\x1bbuf/validate/validate.proto\"\x96\x01\n" +
	"\fMainManifest\x123\n" +
	"\x04name\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04name\x12\x14\n" +
	"\x05setup\x18\x02 \x01(\bR\x05setup\x12;\n" +
	"\aservers\x18\x03 \x03(\v2\x17.malonaz.onyx.v1.ServerB\b\xbaH\x05\x92\x01\x02\b\x01R\aservers\"\x80\a\n" +
	"\x06Server\x123\n" +
	"\x04name\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04name\x122\n" +
	"\x04grpc\x18\x02 \x01(\v2\x1c.malonaz.onyx.v1.Server.GrpcH\x00R\x04grpc\x122\n" +
	"\x04http\x18\x03 \x01(\v2\x1c.malonaz.onyx.v1.Server.HttpH\x00R\x04http\x12L\n" +
	"\x0egrpc_web_proxy\x18\x04 \x01(\v2$.malonaz.onyx.v1.Server.GrpcWebProxyH\x00R\fgrpcWebProxy\x12A\n" +
	"\tprocessor\x18\x05 \x01(\v2!.malonaz.onyx.v1.Server.ProcessorH\x00R\tprocessor\x1a\xf1\x02\n" +
	"\x04Grpc\x12Q\n" +
	"\finterceptors\x18\x01 \x03(\x0e2\x1c.malonaz.onyx.v1.InterceptorB\x0f\xbaH\f\x92\x01\t\"\a\x82\x01\x04\x10\x01 \x00R\finterceptors\x12%\n" +
	"\x0edescriptor_set\x18\x02 \x01(\tR\rdescriptorSet\x12J\n" +
	"\bservices\x18\x03 \x03(\v2$.malonaz.onyx.v1.Server.Grpc.ServiceB\b\xbaH\x05\x92\x01\x02\b\x01R\bservices\x1a\xa2\x01\n" +
	"\aService\x12\x1d\n" +
	"\x05proto\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05proto\x129\n" +
	"\aservice\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\aservice\x12#\n" +
	"\bmanifest\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmanifest\x12\x18\n" +
	"\agateway\x18\x04 \x01(\bR\agateway\x1a\x82\x01\n" +
	"\x04Http\x12J\n" +
	"\bservices\x18\x01 \x03(\v2$.malonaz.onyx.v1.Server.Http.ServiceB\b\xbaH\x05\x92\x01\x02\b\x01R\bservices\x1a.\n" +
	"\aService\x12#\n" +
	"\bmanifest\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmanifest\x1a\x0e\n" +
	"\fGrpcWebProxy\x1a0\n" +
	"\tProcessor\x12#\n" +
	"\bmanifest\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmanifestB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01*\xe4\x02\n" +
	"\vInterceptor\x12\x1b\n" +
	"\x17INTERCEPTOR_UNSPECIFIED\x10\x00\x12.\n" +
	"*INTERCEPTOR_SESSION_LOCAL_CONTEXT_INJECTOR\x10\x01\x12/\n" +
	"+INTERCEPTOR_EXTERNAL_API_KEY_AUTHENTICATION\x10\x02\x12/\n" +
	"+INTERCEPTOR_INTERNAL_SERVICE_AUTHENTICATION\x10\x03\x12\"\n" +
	"\x1eINTERCEPTOR_JWT_AUTHENTICATION\x10\x04\x12)\n" +
	"%INTERCEPTOR_PERMISSION_AUTHENTICATION\x10\x05\x12$\n" +
	" INTERCEPTOR_SESSION_LOG_INJECTOR\x10\x06\x121\n" +
	"-INTERCEPTOR_SESSION_OUTGOING_CONTEXT_INJECTOR\x10\aB*Z(github.com/malonaz/core/genproto/onyx/v1b\x06proto3"

var file_malonaz_onyx_v1_main_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_malonaz_onyx_v1_main_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_malonaz_onyx_v1_main_proto_goTypes = []any{
	(Interceptor)(0),            // 0: malonaz.onyx.v1.Interceptor
	(*MainManifest)(nil),        // 1: malonaz.onyx.v1.MainManifest
	(*Server)(nil),              // 2: malonaz.onyx.v1.Server
	(*Server_Grpc)(nil),         // 3: malonaz.onyx.v1.Server.Grpc
	(*Server_Http)(nil),         // 4: malonaz.onyx.v1.Server.Http
	(*Server_GrpcWebProxy)(nil), // 5: malonaz.onyx.v1.Server.GrpcWebProxy
	(*Server_Processor)(nil),    // 6: malonaz.onyx.v1.Server.Processor
	(*Server_Grpc_Service)(nil), // 7: malonaz.onyx.v1.Server.Grpc.Service
	(*Server_Http_Service)(nil), // 8: malonaz.onyx.v1.Server.Http.Service
}
var file_malonaz_onyx_v1_main_proto_depIdxs = []int32{
	2, // 0: malonaz.onyx.v1.MainManifest.servers:type_name -> malonaz.onyx.v1.Server
	3, // 1: malonaz.onyx.v1.Server.grpc:type_name -> malonaz.onyx.v1.Server.Grpc
	4, // 2: malonaz.onyx.v1.Server.http:type_name -> malonaz.onyx.v1.Server.Http
	5, // 3: malonaz.onyx.v1.Server.grpc_web_proxy:type_name -> malonaz.onyx.v1.Server.GrpcWebProxy
	6, // 4: malonaz.onyx.v1.Server.processor:type_name -> malonaz.onyx.v1.Server.Processor
	0, // 5: malonaz.onyx.v1.Server.Grpc.interceptors:type_name -> malonaz.onyx.v1.Interceptor
	7, // 6: malonaz.onyx.v1.Server.Grpc.services:type_name -> malonaz.onyx.v1.Server.Grpc.Service
	8, // 7: malonaz.onyx.v1.Server.Http.services:type_name -> malonaz.onyx.v1.Server.Http.Service
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_malonaz_onyx_v1_main_proto_init() }
func file_malonaz_onyx_v1_main_proto_init() {
	if File_malonaz_onyx_v1_main_proto != nil {
		return
	}
	file_malonaz_onyx_v1_main_proto_msgTypes[1].OneofWrappers = []any{
		(*server_Grpc_)(nil),
		(*server_Http_)(nil),
		(*server_GrpcWebProxy_)(nil),
		(*server_Processor_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malonaz_onyx_v1_main_proto_rawDesc), len(file_malonaz_onyx_v1_main_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_malonaz_onyx_v1_main_proto_goTypes,
		DependencyIndexes: file_malonaz_onyx_v1_main_proto_depIdxs,
		EnumInfos:         file_malonaz_onyx_v1_main_proto_enumTypes,
		MessageInfos:      file_malonaz_onyx_v1_main_proto_msgTypes,
	}.Build()
	File_malonaz_onyx_v1_main_proto = out.File
	file_malonaz_onyx_v1_main_proto_goTypes = nil
	file_malonaz_onyx_v1_main_proto_depIdxs = nil
}
