// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file malonaz/onyx/v1/main.proto (package malonaz.onyx.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file malonaz/onyx/v1/main.proto.
 */
export const file_malonaz_onyx_v1_main: GenFile = /*@__PURE__*/
  fileDesc("ChptYWxvbmF6L29ueXgvdjEvbWFpbi5wcm90bxIPbWFsb25hei5vbnl4LnYxIoABCgxNYWluTWFuaWZlc3QSLQoEbmFtZRgBIAEoCUIfukgcchoyGF5bYS16MC05XSsoLVthLXowLTldKykqJBINCgVzZXR1cBgCIAEoCBIyCgdzZXJ2ZXJzGAMgAygLMhcubWFsb25hei5vbnl4LnYxLlNlcnZlckIIukgFkgECCAEi6wUKBlNlcnZlchItCgRuYW1lGAEgASgJQh+6SBxyGjIYXlthLXowLTldKygtW2EtejAtOV0rKSokEiwKBGdycGMYAiABKAsyHC5tYWxvbmF6Lm9ueXgudjEuU2VydmVyLkdycGNIABIsCgRodHRwGAMgASgLMhwubWFsb25hei5vbnl4LnYxLlNlcnZlci5IdHRwSAASPgoOZ3JwY193ZWJfcHJveHkYBCABKAsyJC5tYWxvbmF6Lm9ueXgudjEuU2VydmVyLkdycGNXZWJQcm94eUgAEjYKCXByb2Nlc3NvchgFIAEoCzIhLm1hbG9uYXoub255eC52MS5TZXJ2ZXIuUHJvY2Vzc29ySAAapgIKBEdycGMSQwoMaW50ZXJjZXB0b3JzGAEgAygOMhwubWFsb25hei5vbnl4LnYxLkludGVyY2VwdG9yQg+6SAySAQkiB4IBBBABIAASFgoOZGVzY3JpcHRvcl9zZXQYAiABKAkSQAoIc2VydmljZXMYAyADKAsyJC5tYWxvbmF6Lm9ueXgudjEuU2VydmVyLkdycGMuU2VydmljZUIIukgFkgECCAEafwoHU2VydmljZRIWCgVwcm90bxgBIAEoCUIHukgEcgIQARIwCgdzZXJ2aWNlGAIgASgJQh+6SBxyGjIYXlthLXowLTldKygtW2EtejAtOV0rKSokEhkKCG1hbmlmZXN0GAMgASgJQge6SARyAhABEg8KB2dhdGV3YXkYBCABKAgabgoESHR0cBJACghzZXJ2aWNlcxgBIAMoCzIkLm1hbG9uYXoub255eC52MS5TZXJ2ZXIuSHR0cC5TZXJ2aWNlQgi6SAWSAQIIARokCgdTZXJ2aWNlEhkKCG1hbmlmZXN0GAEgASgJQge6SARyAhABGg4KDEdycGNXZWJQcm94eRomCglQcm9jZXNzb3ISGQoIbWFuaWZlc3QYASABKAlCB7pIBHICEAFCDQoEa2luZBIFukgCCAEq5AIKC0ludGVyY2VwdG9yEhsKF0lOVEVSQ0VQVE9SX1VOU1BFQ0lGSUVEEAASLgoqSU5URVJDRVBUT1JfU0VTU0lPTl9MT0NBTF9DT05URVhUX0lOSkVDVE9SEAESLworSU5URVJDRVBUT1JfRVhURVJOQUxfQVBJX0tFWV9BVVRIRU5USUNBVElPThACEi8KK0lOVEVSQ0VQVE9SX0lOVEVSTkFMX1NFUlZJQ0VfQVVUSEVOVElDQVRJT04QAxIiCh5JTlRFUkNFUFRPUl9KV1RfQVVUSEVOVElDQVRJT04QBBIpCiVJTlRFUkNFUFRPUl9QRVJNSVNTSU9OX0FVVEhFTlRJQ0FUSU9OEAUSJAogSU5URVJDRVBUT1JfU0VTU0lPTl9MT0dfSU5KRUNUT1IQBhIxCi1JTlRFUkNFUFRPUl9TRVNTSU9OX09VVEdPSU5HX0NPTlRFWFRfSU5KRUNUT1IQB0IqWihnaXRodWIuY29tL21hbG9uYXovY29yZS9nZW5wcm90by9vbnl4L3YxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * A Go binary: the servers composing services, and the flags and wiring generated for them.
 *
 * @generated from message malonaz.onyx.v1.MainManifest
 */
export type MainManifest = Message<"malonaz.onyx.v1.MainManifest"> & {
  /**
   * Kebab-case name of the binary.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The package defines `setup(ctx) error`, run before anything starts (e.g. migrations).
   *
   * @generated from field: bool setup = 2;
   */
  setup: boolean;

  /**
   * Started in dependency order: a server after every server it dials in-process.
   *
   * @generated from field: repeated malonaz.onyx.v1.Server servers = 3;
   */
  servers: Server[];
};

export type MainManifestValid = MainManifest;

/**
 * Describes the message malonaz.onyx.v1.MainManifest.
 * Use `create(MainManifestSchema)` to create a new message.
 */
export const MainManifestSchema: GenMessage<MainManifest, {validType: MainManifestValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 0);

/**
 * A server of the binary.
 *
 * @generated from message malonaz.onyx.v1.Server
 */
export type Server = Message<"malonaz.onyx.v1.Server"> & {
  /**
   * Kebab-case. The flag namespace (`{name}-grpc`, `{name}-http`, ...) and health entry of the server.
   * A gRPC server named after the one service it serves shares that service's flags.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Which kind.
   *
   * @generated from oneof malonaz.onyx.v1.Server.kind
   */
  kind: {
    /**
     * A gRPC server.
     *
     * @generated from field: malonaz.onyx.v1.Server.Grpc grpc = 2;
     */
    value: Server_Grpc;
    case: "grpc";
  } | {
    /**
     * An HTTP server.
     *
     * @generated from field: malonaz.onyx.v1.Server.Http http = 3;
     */
    value: Server_Http;
    case: "http";
  } | {
    /**
     * A grpc-web to gRPC proxy.
     *
     * @generated from field: malonaz.onyx.v1.Server.GrpcWebProxy grpc_web_proxy = 4;
     */
    value: Server_GrpcWebProxy;
    case: "grpcWebProxy";
  } | {
    /**
     * A service with no listener.
     *
     * @generated from field: malonaz.onyx.v1.Server.Processor processor = 5;
     */
    value: Server_Processor;
    case: "processor";
  } | { case: undefined; value?: undefined };
};

export type ServerValid = Server;

/**
 * Describes the message malonaz.onyx.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export const ServerSchema: GenMessage<Server, {validType: ServerValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1);

/**
 * A gRPC server.
 *
 * @generated from message malonaz.onyx.v1.Server.Grpc
 */
export type Server_Grpc = Message<"malonaz.onyx.v1.Server.Grpc"> & {
  /**
   * Outermost first.
   *
   * @generated from field: repeated malonaz.onyx.v1.Interceptor interceptors = 1;
   */
  interceptors: Interceptor[];

  /**
   * Path, relative to the main package, of a FileDescriptorSet to embed for reflection.
   *
   * @generated from field: string descriptor_set = 2;
   */
  descriptorSet: string;

  /**
   * Services registered on this server.
   *
   * @generated from field: repeated malonaz.onyx.v1.Server.Grpc.Service services = 3;
   */
  services: Server_Grpc_Service[];
};

export type Server_GrpcValid = Server_Grpc;

/**
 * Describes the message malonaz.onyx.v1.Server.Grpc.
 * Use `create(Server_GrpcSchema)` to create a new message.
 */
export const Server_GrpcSchema: GenMessage<Server_Grpc, {validType: Server_GrpcValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1, 0);

/**
 * A gRPC service registered on the server.
 *
 * @generated from message malonaz.onyx.v1.Server.Grpc.Service
 */
export type Server_Grpc_Service = Message<"malonaz.onyx.v1.Server.Grpc.Service"> & {
  /**
   * Please label of the proto library declaring the service.
   *
   * @generated from field: string proto = 1;
   */
  proto: string;

  /**
   * Kebab-case name of the proto service.
   *
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * Please label of the ServiceManifest implementing it.
   *
   * @generated from field: string manifest = 3;
   */
  manifest: string;

  /**
   * Also serve it over HTTP through grpc-gateway.
   *
   * @generated from field: bool gateway = 4;
   */
  gateway: boolean;
};

export type Server_Grpc_ServiceValid = Server_Grpc_Service;

/**
 * Describes the message malonaz.onyx.v1.Server.Grpc.Service.
 * Use `create(Server_Grpc_ServiceSchema)` to create a new message.
 */
export const Server_Grpc_ServiceSchema: GenMessage<Server_Grpc_Service, {validType: Server_Grpc_ServiceValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1, 0, 0);

/**
 * An HTTP server.
 *
 * @generated from message malonaz.onyx.v1.Server.Http
 */
export type Server_Http = Message<"malonaz.onyx.v1.Server.Http"> & {
  /**
   * Services registering routes on this server.
   *
   * @generated from field: repeated malonaz.onyx.v1.Server.Http.Service services = 1;
   */
  services: Server_Http_Service[];
};

export type Server_HttpValid = Server_Http;

/**
 * Describes the message malonaz.onyx.v1.Server.Http.
 * Use `create(Server_HttpSchema)` to create a new message.
 */
export const Server_HttpSchema: GenMessage<Server_Http, {validType: Server_HttpValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1, 1);

/**
 * A service registering routes on the server.
 *
 * @generated from message malonaz.onyx.v1.Server.Http.Service
 */
export type Server_Http_Service = Message<"malonaz.onyx.v1.Server.Http.Service"> & {
  /**
   * Please label of the ServiceManifest; its Service must implement RegisterRoutes.
   *
   * @generated from field: string manifest = 1;
   */
  manifest: string;
};

export type Server_Http_ServiceValid = Server_Http_Service;

/**
 * Describes the message malonaz.onyx.v1.Server.Http.Service.
 * Use `create(Server_Http_ServiceSchema)` to create a new message.
 */
export const Server_Http_ServiceSchema: GenMessage<Server_Http_Service, {validType: Server_Http_ServiceValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1, 1, 0);

/**
 * A grpc-web to gRPC proxy; the backend is configured by its own flags.
 *
 * @generated from message malonaz.onyx.v1.Server.GrpcWebProxy
 */
export type Server_GrpcWebProxy = Message<"malonaz.onyx.v1.Server.GrpcWebProxy"> & {
};

export type Server_GrpcWebProxyValid = Server_GrpcWebProxy;

/**
 * Describes the message malonaz.onyx.v1.Server.GrpcWebProxy.
 * Use `create(Server_GrpcWebProxySchema)` to create a new message.
 */
export const Server_GrpcWebProxySchema: GenMessage<Server_GrpcWebProxy, {validType: Server_GrpcWebProxyValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1, 2);

/**
 * A service with no listener: started and health-checked, nothing more.
 *
 * @generated from message malonaz.onyx.v1.Server.Processor
 */
export type Server_Processor = Message<"malonaz.onyx.v1.Server.Processor"> & {
  /**
   * Please label of the ServiceManifest.
   *
   * @generated from field: string manifest = 1;
   */
  manifest: string;
};

export type Server_ProcessorValid = Server_Processor;

/**
 * Describes the message malonaz.onyx.v1.Server.Processor.
 * Use `create(Server_ProcessorSchema)` to create a new message.
 */
export const Server_ProcessorSchema: GenMessage<Server_Processor, {validType: Server_ProcessorValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_onyx_v1_main, 1, 3);

/**
 * A gRPC server interceptor.
 *
 * @generated from enum malonaz.onyx.v1.Interceptor
 */
export enum Interceptor {
  /**
   * Used to detect an unset field.
   *
   * @generated from enum value: INTERCEPTOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Gives the session manager a local context for the request.
   *
   * @generated from enum value: INTERCEPTOR_SESSION_LOCAL_CONTEXT_INJECTOR = 1;
   */
  SESSION_LOCAL_CONTEXT_INJECTOR = 1,

  /**
   * Authenticates external callers by API key.
   *
   * @generated from enum value: INTERCEPTOR_EXTERNAL_API_KEY_AUTHENTICATION = 2;
   */
  EXTERNAL_API_KEY_AUTHENTICATION = 2,

  /**
   * Authenticates internal services by shared secret.
   *
   * @generated from enum value: INTERCEPTOR_INTERNAL_SERVICE_AUTHENTICATION = 3;
   */
  INTERNAL_SERVICE_AUTHENTICATION = 3,

  /**
   * Authenticates callers by JWT.
   *
   * @generated from enum value: INTERCEPTOR_JWT_AUTHENTICATION = 4;
   */
  JWT_AUTHENTICATION = 4,

  /**
   * Authorizes the authenticated session against the method's permissions.
   *
   * @generated from enum value: INTERCEPTOR_PERMISSION_AUTHENTICATION = 5;
   */
  PERMISSION_AUTHENTICATION = 5,

  /**
   * Adds the session to the request log fields.
   *
   * @generated from enum value: INTERCEPTOR_SESSION_LOG_INJECTOR = 6;
   */
  SESSION_LOG_INJECTOR = 6,

  /**
   * Propagates the session on outgoing calls.
   *
   * @generated from enum value: INTERCEPTOR_SESSION_OUTGOING_CONTEXT_INJECTOR = 7;
   */
  SESSION_OUTGOING_CONTEXT_INJECTOR = 7,
}

/**
 * Describes the enum malonaz.onyx.v1.Interceptor.
 */
export const InterceptorSchema: GenEnum<Interceptor> = /*@__PURE__*/
  enumDesc(file_malonaz_onyx_v1_main, 0);

