# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: malonaz/onyx/v1/onyx.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'malonaz/onyx/v1/onyx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amalonaz/onyx/v1/onyx.proto\x12\x0fmalonaz.onyx.v1\"\xf9\x01\n\nObjectMeta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\x06labels\x18\x02 \x03(\x0b\x32\'.malonaz.onyx.v1.ObjectMeta.LabelsEntry\x12\x41\n\x0b\x61nnotations\x18\x03 \x03(\x0b\x32,.malonaz.onyx.v1.ObjectMeta.AnnotationsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfb\x01\n\x0e\x44\x65pendencySpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\x0bgrpc_client\x18\x02 \x01(\x0b\x32%.malonaz.onyx.v1.GrpcClientDependencyH\x00\x12\x44\n\x0fpostgres_client\x18\x03 \x01(\x0b\x32).malonaz.onyx.v1.PostgresClientDependencyH\x00\x12I\n\x12postgres_db_client\x18\x04 \x01(\x0b\x32+.malonaz.onyx.v1.PostgresDbClientDependencyH\x00\x42\x0c\n\ndependency\"%\n\x14GrpcClientDependency\x12\r\n\x05proto\x18\x01 \x01(\t\"2\n\x18PostgresClientDependency\x12\x16\n\x0eimplementation\x18\x01 \x01(\t\"4\n\x1aPostgresDbClientDependency\x12\x16\n\x0eimplementation\x18\x01 \x01(\tB*Z(github.com/malonaz/core/genproto/onyx/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'malonaz.onyx.v1.onyx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/malonaz/core/genproto/onyx/v1'
  _globals['_OBJECTMETA_LABELSENTRY']._loaded_options = None
  _globals['_OBJECTMETA_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_OBJECTMETA_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_OBJECTMETA_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_OBJECTMETA']._serialized_start=48
  _globals['_OBJECTMETA']._serialized_end=297
  _globals['_OBJECTMETA_LABELSENTRY']._serialized_start=200
  _globals['_OBJECTMETA_LABELSENTRY']._serialized_end=245
  _globals['_OBJECTMETA_ANNOTATIONSENTRY']._serialized_start=247
  _globals['_OBJECTMETA_ANNOTATIONSENTRY']._serialized_end=297
  _globals['_DEPENDENCYSPEC']._serialized_start=300
  _globals['_DEPENDENCYSPEC']._serialized_end=551
  _globals['_GRPCCLIENTDEPENDENCY']._serialized_start=553
  _globals['_GRPCCLIENTDEPENDENCY']._serialized_end=590
  _globals['_POSTGRESCLIENTDEPENDENCY']._serialized_start=592
  _globals['_POSTGRESCLIENTDEPENDENCY']._serialized_end=642
  _globals['_POSTGRESDBCLIENTDEPENDENCY']._serialized_start=644
  _globals['_POSTGRESDBCLIENTDEPENDENCY']._serialized_end=696
# @@protoc_insertion_point(module_scope)
