// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file malonaz/aip/v1/annotation.proto (package malonaz.aip.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file malonaz/aip/v1/annotation.proto.
 */
export const file_malonaz_aip_v1_annotation: GenFile = /*@__PURE__*/
  fileDesc("Ch9tYWxvbmF6L2FpcC92MS9hbm5vdGF0aW9uLnByb3RvEg5tYWxvbmF6LmFpcC52MSK1AQoKQW5ub3RhdGlvbhJ2CgNrZXkYASABKAlCabpIZnJkEAEyYF4oW2EtekEtWjAtOV0oW2EtekEtWjAtOS4tXXswLDI1MX1bYS16QS1aMC05XSk/Lyk/W2EtekEtWjAtOV0oW2EtekEtWjAtOV8uLV17MCw2MX1bYS16QS1aMC05XSk/JBIbCgtkZXNjcmlwdGlvbhgCIAEoCUIGukgDyAEBEhIKCnZhbHVlX3R5cGUYAyABKAlCKVonZ2l0aHViLmNvbS9tYWxvbmF6L2NvcmUvZ2VucHJvdG8vYWlwL3YxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * An annotation definition declared by a service. Annotations are bookkeeping
 * written by tooling, never by users; unlike labels they are not filterable and
 * their values are free-form.
 *
 * @generated from message malonaz.aip.v1.Annotation
 */
export type Annotation = Message<"malonaz.aip.v1.Annotation"> & {
  /**
   * The annotation key, e.g. "google.calendar.onikisu.com/updated".
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Human-readable description of the annotation's purpose.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Fully-qualified name of the message the value is: proto-encoded and base64 in the
   * string map, e.g. "google.protobuf.Timestamp". May be package-relative like AIP-151's
   * operation_info.response_type. Unset means the value is a plain string.
   *
   * @generated from field: string value_type = 3;
   */
  valueType: string;
};

/**
 * An annotation definition declared by a service. Annotations are bookkeeping
 * written by tooling, never by users; unlike labels they are not filterable and
 * their values are free-form.
 *
 * @generated from message malonaz.aip.v1.Annotation
 */
export type AnnotationValid = Message<"malonaz.aip.v1.Annotation"> & {
  /**
   * The annotation key, e.g. "google.calendar.onikisu.com/updated".
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Human-readable description of the annotation's purpose.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Fully-qualified name of the message the value is: proto-encoded and base64 in the
   * string map, e.g. "google.protobuf.Timestamp". May be package-relative like AIP-151's
   * operation_info.response_type. Unset means the value is a plain string.
   *
   * @generated from field: string value_type = 3;
   */
  valueType: string;
};

/**
 * Describes the message malonaz.aip.v1.Annotation.
 * Use `create(AnnotationSchema)` to create a new message.
 */
export const AnnotationSchema: GenMessage<Annotation, {validType: AnnotationValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_aip_v1_annotation, 0);

