// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file malonaz/aip/v1/label.proto (package malonaz.aip.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file malonaz/aip/v1/label.proto.
 */
export const file_malonaz_aip_v1_label: GenFile = /*@__PURE__*/
  fileDesc("ChptYWxvbmF6L2FpcC92MS9sYWJlbC5wcm90bxIObWFsb25hei5haXAudjEizwEKBUxhYmVsEnYKA2tleRgBIAEoCUJpukhmcmQQATJgXihbYS16QS1aMC05XShbYS16QS1aMC05Li1dezAsMjUxfVthLXpBLVowLTldKT8vKT9bYS16QS1aMC05XShbYS16QS1aMC05Xy4tXXswLDYxfVthLXpBLVowLTldKT8kEhsKC2Rlc2NyaXB0aW9uGAIgASgJQga6SAPIAQESMQoGdmFsdWVzGAMgAygJQiG6SB6SARsiGXIXGD8yE15bYS16MC05X1wtXHB7TH1dKiRCKVonZ2l0aHViLmNvbS9tYWxvbmF6L2NvcmUvZ2VucHJvdG8vYWlwL3YxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * A label definition declared by a service.
 *
 * @generated from message malonaz.aip.v1.Label
 */
export type Label = Message<"malonaz.aip.v1.Label"> & {
  /**
   * The label key, e.g. "user.onikisu.com/last-sync".
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Human-readable description of the label's purpose.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Optional allowed values. If empty, any value is accepted.
   *
   * @generated from field: repeated string values = 3;
   */
  values: string[];
};

/**
 * A label definition declared by a service.
 *
 * @generated from message malonaz.aip.v1.Label
 */
export type LabelValid = Message<"malonaz.aip.v1.Label"> & {
  /**
   * The label key, e.g. "user.onikisu.com/last-sync".
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Human-readable description of the label's purpose.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Optional allowed values. If empty, any value is accepted.
   *
   * @generated from field: repeated string values = 3;
   */
  values: string[];
};

/**
 * Describes the message malonaz.aip.v1.Label.
 * Use `create(LabelSchema)` to create a new message.
 */
export const LabelSchema: GenMessage<Label, {validType: LabelValid}> = /*@__PURE__*/
  messageDesc(file_malonaz_aip_v1_label, 0);

