// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: malonaz/aip/v1/label.proto

//go:build !protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A label definition declared by a service.
type Label struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The label key, e.g. "user.onikisu.com/last-sync".
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human-readable description of the label's purpose.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Optional allowed values. If empty, any value is accepted.
	Values        []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_malonaz_aip_v1_label_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_aip_v1_label_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Label) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Label) SetKey(v string) {
	x.Key = v
}

func (x *Label) SetDescription(v string) {
	x.Description = v
}

func (x *Label) SetValues(v []string) {
	x.Values = v
}

type Label_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The label key, e.g. "user.onikisu.com/last-sync".
	Key string
	// Human-readable description of the label's purpose.
	Description string
	// Optional allowed values. If empty, any value is accepted.
	Values []string
}

func (b0 Label_builder) Build() *Label {
	m0 := &Label{}
	b, x := &b0, m0
	_, _ = b, x
	x.Key = b.Key
	x.Description = b.Description
	x.Values = b.Values
	return m0
}

var File_malonaz_aip_v1_label_proto protoreflect.FileDescriptor

const file_malonaz_aip_v1_label_proto_rawDesc = "" +
	"\n" +
	"\x1amalonaz/aip/v1/label.proto\x12\x0emalonaz.aip.v1\x1a\x1bbuf/validate/validate.proto\"\xe9\x01\n" +
	"\x05Label\x12{\n" +
	"\x03key\x18\x01 \x01(\tBi\xbaHfrd\x10\x012`^([a-zA-Z0-9]([a-zA-Z0-9.-]{0,251}[a-zA-Z0-9])?/)?[a-zA-Z0-9]([a-zA-Z0-9_.-]{0,61}[a-zA-Z0-9])?$R\x03key\x12(\n" +
	"\vdescription\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdescription\x129\n" +
	"\x06values\x18\x03 \x03(\tB!\xbaH\x1e\x92\x01\x1b\"\x19r\x17\x18?2\x13^[a-z0-9_\\-\\p{L}]*$R\x06valuesB)Z'github.com/malonaz/core/genproto/aip/v1b\x06proto3"

var file_malonaz_aip_v1_label_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_malonaz_aip_v1_label_proto_goTypes = []any{
	(*Label)(nil), // 0: malonaz.aip.v1.Label
}
var file_malonaz_aip_v1_label_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_malonaz_aip_v1_label_proto_init() }
func file_malonaz_aip_v1_label_proto_init() {
	if File_malonaz_aip_v1_label_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malonaz_aip_v1_label_proto_rawDesc), len(file_malonaz_aip_v1_label_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_malonaz_aip_v1_label_proto_goTypes,
		DependencyIndexes: file_malonaz_aip_v1_label_proto_depIdxs,
		MessageInfos:      file_malonaz_aip_v1_label_proto_msgTypes,
	}.Build()
	File_malonaz_aip_v1_label_proto = out.File
	file_malonaz_aip_v1_label_proto_goTypes = nil
	file_malonaz_aip_v1_label_proto_depIdxs = nil
}
