// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.0
// source: ai/v1/jsonschema.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a JSON Schema (recursive definition)
type JsonSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the data type: "object", "string", "number", "integer", "boolean", "array", "null"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Human-readable description of what this schema represents
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// For objects
	// Defines the properties of an object type, where each property has its own schema (recursive)
	Properties map[string]*JsonSchema `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// List of property names that must be present in the object
	Required []string `protobuf:"bytes,4,rep,name=required,proto3" json:"required,omitempty"`
	// For arrays
	// Defines the schema for elements within an array (recursive)
	Items *JsonSchema `protobuf:"bytes,5,opt,name=items,proto3" json:"items,omitempty"`
	// Minimum number of items required in the array
	MinItems *int32 `protobuf:"varint,6,opt,name=min_items,json=minItems,proto3,oneof" json:"min_items,omitempty"`
	// Maximum number of items allowed in the array
	MaxItems *int32 `protobuf:"varint,7,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	// For strings
	// List of allowed string values (enumeration constraint)
	Enum []string `protobuf:"bytes,8,rep,name=enum,proto3" json:"enum,omitempty"`
	// Minimum length of the string
	MinLength *int32 `protobuf:"varint,9,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	// Maximum length of the string
	MaxLength *int32 `protobuf:"varint,10,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	// Regular expression pattern the string must match
	Pattern *string `protobuf:"bytes,11,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	// Semantic format hint: "date-time", "email", "uri", "uuid", etc.
	Format *string `protobuf:"bytes,12,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// For numbers
	// Minimum value (inclusive) for number or integer types
	Minimum *float64 `protobuf:"fixed64,13,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	// Maximum value (inclusive) for number or integer types
	Maximum *float64 `protobuf:"fixed64,14,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	// Minimum value (exclusive) for number or integer types
	ExclusiveMinimum *float64 `protobuf:"fixed64,15,opt,name=exclusive_minimum,json=exclusiveMinimum,proto3,oneof" json:"exclusive_minimum,omitempty"`
	// Maximum value (exclusive) for number or integer types
	ExclusiveMaximum *float64 `protobuf:"fixed64,16,opt,name=exclusive_maximum,json=exclusiveMaximum,proto3,oneof" json:"exclusive_maximum,omitempty"`
	// The number must be a multiple of this value
	MultipleOf *float64 `protobuf:"fixed64,17,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	// Default value to use when no value is provided
	Default *string `protobuf:"bytes,18,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Example values that satisfy this schema (for documentation)
	Examples []string `protobuf:"bytes,19,rep,name=examples,proto3" json:"examples,omitempty"`
	// Advanced combinators
	// Schema is valid if it matches ANY of the provided schemas (recursive)
	AnyOf []*JsonSchema `protobuf:"bytes,20,rep,name=any_of,json=anyOf,proto3" json:"any_of,omitempty"`
	// Schema is valid if it matches EXACTLY ONE of the provided schemas (recursive)
	OneOf []*JsonSchema `protobuf:"bytes,21,rep,name=one_of,json=oneOf,proto3" json:"one_of,omitempty"`
	// Schema is valid if it matches ALL of the provided schemas (recursive)
	AllOf []*JsonSchema `protobuf:"bytes,22,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"`
	// Schema is valid if it does NOT match the provided schema (recursive)
	Not           *JsonSchema `protobuf:"bytes,23,opt,name=not,proto3" json:"not,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonSchema) Reset() {
	*x = JsonSchema{}
	mi := &file_ai_v1_jsonschema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonSchema) ProtoMessage() {}

func (x *JsonSchema) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_jsonschema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonSchema.ProtoReflect.Descriptor instead.
func (*JsonSchema) Descriptor() ([]byte, []int) {
	return file_ai_v1_jsonschema_proto_rawDescGZIP(), []int{0}
}

func (x *JsonSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JsonSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JsonSchema) GetProperties() map[string]*JsonSchema {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *JsonSchema) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *JsonSchema) GetItems() *JsonSchema {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *JsonSchema) GetMinItems() int32 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	return 0
}

func (x *JsonSchema) GetMaxItems() int32 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

func (x *JsonSchema) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *JsonSchema) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *JsonSchema) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *JsonSchema) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *JsonSchema) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *JsonSchema) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *JsonSchema) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *JsonSchema) GetExclusiveMinimum() float64 {
	if x != nil && x.ExclusiveMinimum != nil {
		return *x.ExclusiveMinimum
	}
	return 0
}

func (x *JsonSchema) GetExclusiveMaximum() float64 {
	if x != nil && x.ExclusiveMaximum != nil {
		return *x.ExclusiveMaximum
	}
	return 0
}

func (x *JsonSchema) GetMultipleOf() float64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

func (x *JsonSchema) GetDefault() string {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return ""
}

func (x *JsonSchema) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *JsonSchema) GetAnyOf() []*JsonSchema {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

func (x *JsonSchema) GetOneOf() []*JsonSchema {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *JsonSchema) GetAllOf() []*JsonSchema {
	if x != nil {
		return x.AllOf
	}
	return nil
}

func (x *JsonSchema) GetNot() *JsonSchema {
	if x != nil {
		return x.Not
	}
	return nil
}

var File_ai_v1_jsonschema_proto protoreflect.FileDescriptor

const file_ai_v1_jsonschema_proto_rawDesc = "" +
	"\n" +
	"\x16ai/v1/jsonschema.proto\x12\x12malonaz.core.ai.v1\x1a\x1bbuf/validate/validate.proto\"\xe8\t\n" +
	"\n" +
	"JsonSchema\x12P\n" +
	"\x04type\x18\x01 \x01(\tB<\xbaH9r7R\x06objectR\x06stringR\x06numberR\aintegerR\abooleanR\x05arrayR\x04nullR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12N\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2..malonaz.core.ai.v1.JsonSchema.PropertiesEntryR\n" +
	"properties\x12\x1a\n" +
	"\brequired\x18\x04 \x03(\tR\brequired\x124\n" +
	"\x05items\x18\x05 \x01(\v2\x1e.malonaz.core.ai.v1.JsonSchemaR\x05items\x12 \n" +
	"\tmin_items\x18\x06 \x01(\x05H\x00R\bminItems\x88\x01\x01\x12 \n" +
	"\tmax_items\x18\a \x01(\x05H\x01R\bmaxItems\x88\x01\x01\x12\x12\n" +
	"\x04enum\x18\b \x03(\tR\x04enum\x12\"\n" +
	"\n" +
	"min_length\x18\t \x01(\x05H\x02R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\n" +
	" \x01(\x05H\x03R\tmaxLength\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\v \x01(\tH\x04R\apattern\x88\x01\x01\x12\x1b\n" +
	"\x06format\x18\f \x01(\tH\x05R\x06format\x88\x01\x01\x12\x1d\n" +
	"\aminimum\x18\r \x01(\x01H\x06R\aminimum\x88\x01\x01\x12\x1d\n" +
	"\amaximum\x18\x0e \x01(\x01H\aR\amaximum\x88\x01\x01\x120\n" +
	"\x11exclusive_minimum\x18\x0f \x01(\x01H\bR\x10exclusiveMinimum\x88\x01\x01\x120\n" +
	"\x11exclusive_maximum\x18\x10 \x01(\x01H\tR\x10exclusiveMaximum\x88\x01\x01\x12$\n" +
	"\vmultiple_of\x18\x11 \x01(\x01H\n" +
	"R\n" +
	"multipleOf\x88\x01\x01\x12\x1d\n" +
	"\adefault\x18\x12 \x01(\tH\vR\adefault\x88\x01\x01\x12\x1a\n" +
	"\bexamples\x18\x13 \x03(\tR\bexamples\x125\n" +
	"\x06any_of\x18\x14 \x03(\v2\x1e.malonaz.core.ai.v1.JsonSchemaR\x05anyOf\x125\n" +
	"\x06one_of\x18\x15 \x03(\v2\x1e.malonaz.core.ai.v1.JsonSchemaR\x05oneOf\x125\n" +
	"\x06all_of\x18\x16 \x03(\v2\x1e.malonaz.core.ai.v1.JsonSchemaR\x05allOf\x120\n" +
	"\x03not\x18\x17 \x01(\v2\x1e.malonaz.core.ai.v1.JsonSchemaR\x03not\x1a]\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.malonaz.core.ai.v1.JsonSchemaR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_min_itemsB\f\n" +
	"\n" +
	"_max_itemsB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_lengthB\n" +
	"\n" +
	"\b_patternB\t\n" +
	"\a_formatB\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximumB\x14\n" +
	"\x12_exclusive_minimumB\x14\n" +
	"\x12_exclusive_maximumB\x0e\n" +
	"\f_multiple_ofB\n" +
	"\n" +
	"\b_defaultB(Z&github.com/malonaz/core/genproto/ai/v1b\x06proto3"

var (
	file_ai_v1_jsonschema_proto_rawDescOnce sync.Once
	file_ai_v1_jsonschema_proto_rawDescData []byte
)

func file_ai_v1_jsonschema_proto_rawDescGZIP() []byte {
	file_ai_v1_jsonschema_proto_rawDescOnce.Do(func() {
		file_ai_v1_jsonschema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_jsonschema_proto_rawDesc), len(file_ai_v1_jsonschema_proto_rawDesc)))
	})
	return file_ai_v1_jsonschema_proto_rawDescData
}

var file_ai_v1_jsonschema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_v1_jsonschema_proto_goTypes = []any{
	(*JsonSchema)(nil), // 0: malonaz.core.ai.v1.JsonSchema
	nil,                // 1: malonaz.core.ai.v1.JsonSchema.PropertiesEntry
}
var file_ai_v1_jsonschema_proto_depIdxs = []int32{
	1, // 0: malonaz.core.ai.v1.JsonSchema.properties:type_name -> malonaz.core.ai.v1.JsonSchema.PropertiesEntry
	0, // 1: malonaz.core.ai.v1.JsonSchema.items:type_name -> malonaz.core.ai.v1.JsonSchema
	0, // 2: malonaz.core.ai.v1.JsonSchema.any_of:type_name -> malonaz.core.ai.v1.JsonSchema
	0, // 3: malonaz.core.ai.v1.JsonSchema.one_of:type_name -> malonaz.core.ai.v1.JsonSchema
	0, // 4: malonaz.core.ai.v1.JsonSchema.all_of:type_name -> malonaz.core.ai.v1.JsonSchema
	0, // 5: malonaz.core.ai.v1.JsonSchema.not:type_name -> malonaz.core.ai.v1.JsonSchema
	0, // 6: malonaz.core.ai.v1.JsonSchema.PropertiesEntry.value:type_name -> malonaz.core.ai.v1.JsonSchema
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ai_v1_jsonschema_proto_init() }
func file_ai_v1_jsonschema_proto_init() {
	if File_ai_v1_jsonschema_proto != nil {
		return
	}
	file_ai_v1_jsonschema_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_jsonschema_proto_rawDesc), len(file_ai_v1_jsonschema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_v1_jsonschema_proto_goTypes,
		DependencyIndexes: file_ai_v1_jsonschema_proto_depIdxs,
		MessageInfos:      file_ai_v1_jsonschema_proto_msgTypes,
	}.Build()
	File_ai_v1_jsonschema_proto = out.File
	file_ai_v1_jsonschema_proto_goTypes = nil
	file_ai_v1_jsonschema_proto_depIdxs = nil
}
