// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: malonaz/ai/v1/message.proto

//go:build !protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the level of reasoning effort for AI model responses.
// Controls how many internal reasoning tokens the model generates before
// producing its final response. Higher effort yields more thorough reasoning
// at the cost of increased latency and token usage.
type ReasoningEffort int32

const (
	// Unspecified reasoning effort. Should not be used explicitly.
	ReasoningEffort_REASONING_EFFORT_UNSPECIFIED ReasoningEffort = 0
	// Default reasoning effort as configured by the platform.
	ReasoningEffort_REASONING_EFFORT_DEFAULT ReasoningEffort = 1
	// Low reasoning effort.
	// Prioritizes speed and token efficiency with minimal internal reasoning.
	// Best for simple, straightforward queries.
	ReasoningEffort_REASONING_EFFORT_LOW ReasoningEffort = 2
	// Medium reasoning effort.
	// Balances response speed with reasoning thoroughness.
	// Suitable for most general-purpose queries.
	ReasoningEffort_REASONING_EFFORT_MEDIUM ReasoningEffort = 3
	// High reasoning effort.
	// Maximizes reasoning depth and accuracy by generating more thinking tokens.
	// Best for complex problems requiring careful analysis.
	// May result in slower responses and higher token consumption.
	ReasoningEffort_REASONING_EFFORT_HIGH ReasoningEffort = 4
)

// Enum value maps for ReasoningEffort.
var (
	ReasoningEffort_name = map[int32]string{
		0: "REASONING_EFFORT_UNSPECIFIED",
		1: "REASONING_EFFORT_DEFAULT",
		2: "REASONING_EFFORT_LOW",
		3: "REASONING_EFFORT_MEDIUM",
		4: "REASONING_EFFORT_HIGH",
	}
	ReasoningEffort_value = map[string]int32{
		"REASONING_EFFORT_UNSPECIFIED": 0,
		"REASONING_EFFORT_DEFAULT":     1,
		"REASONING_EFFORT_LOW":         2,
		"REASONING_EFFORT_MEDIUM":      3,
		"REASONING_EFFORT_HIGH":        4,
	}
)

func (x ReasoningEffort) Enum() *ReasoningEffort {
	p := new(ReasoningEffort)
	*p = x
	return p
}

func (x ReasoningEffort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasoningEffort) Descriptor() protoreflect.EnumDescriptor {
	return file_malonaz_ai_v1_message_proto_enumTypes[0].Descriptor()
}

func (ReasoningEffort) Type() protoreflect.EnumType {
	return &file_malonaz_ai_v1_message_proto_enumTypes[0]
}

func (x ReasoningEffort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents the role of a message in a multi-turn AI conversation.
type Role int32

const (
	// Used to detect an unset field.
	Role_ROLE_UNSPECIFIED Role = 0
	// System message.
	Role_ROLE_SYSTEM Role = 1
	// Assistant message.
	Role_ROLE_ASSISTANT Role = 2
	// User message.
	Role_ROLE_USER Role = 3
	// User message.
	Role_ROLE_TOOL Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_SYSTEM",
		2: "ROLE_ASSISTANT",
		3: "ROLE_USER",
		4: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_SYSTEM":      1,
		"ROLE_ASSISTANT":   2,
		"ROLE_USER":        3,
		"ROLE_TOOL":        4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_malonaz_ai_v1_message_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_malonaz_ai_v1_message_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Controls the fidelity level for image processing in vision requests.
type ImageQuality int32

const (
	// Unspecified quality. The provider will use its default setting.
	ImageQuality_IMAGE_QUALITY_UNSPECIFIED ImageQuality = 0
	// Automatic quality selection based on image size and content.
	ImageQuality_IMAGE_QUALITY_AUTO ImageQuality = 1
	// Low fidelity processing for faster, cheaper responses.
	ImageQuality_IMAGE_QUALITY_LOW ImageQuality = 2
	// High fidelity processing for detailed image analysis.
	ImageQuality_IMAGE_QUALITY_HIGH ImageQuality = 3
)

// Enum value maps for ImageQuality.
var (
	ImageQuality_name = map[int32]string{
		0: "IMAGE_QUALITY_UNSPECIFIED",
		1: "IMAGE_QUALITY_AUTO",
		2: "IMAGE_QUALITY_LOW",
		3: "IMAGE_QUALITY_HIGH",
	}
	ImageQuality_value = map[string]int32{
		"IMAGE_QUALITY_UNSPECIFIED": 0,
		"IMAGE_QUALITY_AUTO":        1,
		"IMAGE_QUALITY_LOW":         2,
		"IMAGE_QUALITY_HIGH":        3,
	}
)

func (x ImageQuality) Enum() *ImageQuality {
	p := new(ImageQuality)
	*p = x
	return p
}

func (x ImageQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_malonaz_ai_v1_message_proto_enumTypes[2].Descriptor()
}

func (ImageQuality) Type() protoreflect.EnumType {
	return &file_malonaz_ai_v1_message_proto_enumTypes[2]
}

func (x ImageQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Wrapper message representing any message type in a multi-turn conversation.
// Use this when building conversation histories or streaming message sequences.
type Message struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// When this message was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Arbitrary key-value metadata associated with the message.
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Role of the message sender.
	Role Role `protobuf:"varint,3,opt,name=role,proto3,enum=malonaz.ai.v1.Role" json:"role,omitempty"`
	// The specific message type. Exactly one must be set.
	//
	// Types that are valid to be assigned to Message:
	//
	//	*Message_System
	//	*Message_User
	//	*Message_Assistant
	//	*Message_Tool
	Message       isMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetMessage() isMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetSystem() *SystemMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *Message) GetUser() *UserMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *Message) GetAssistant() *AssistantMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Assistant); ok {
			return x.Assistant
		}
	}
	return nil
}

func (x *Message) GetTool() *ToolResultMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *Message) SetCreateTime(v *timestamppb.Timestamp) {
	x.CreateTime = v
}

func (x *Message) SetMetadata(v map[string]string) {
	x.Metadata = v
}

func (x *Message) SetRole(v Role) {
	x.Role = v
}

func (x *Message) SetSystem(v *SystemMessage) {
	if v == nil {
		x.Message = nil
		return
	}
	x.Message = &Message_System{v}
}

func (x *Message) SetUser(v *UserMessage) {
	if v == nil {
		x.Message = nil
		return
	}
	x.Message = &Message_User{v}
}

func (x *Message) SetAssistant(v *AssistantMessage) {
	if v == nil {
		x.Message = nil
		return
	}
	x.Message = &Message_Assistant{v}
}

func (x *Message) SetTool(v *ToolResultMessage) {
	if v == nil {
		x.Message = nil
		return
	}
	x.Message = &Message_Tool{v}
}

func (x *Message) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return x.CreateTime != nil
}

func (x *Message) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *Message) HasSystem() bool {
	if x == nil {
		return false
	}
	_, ok := x.Message.(*Message_System)
	return ok
}

func (x *Message) HasUser() bool {
	if x == nil {
		return false
	}
	_, ok := x.Message.(*Message_User)
	return ok
}

func (x *Message) HasAssistant() bool {
	if x == nil {
		return false
	}
	_, ok := x.Message.(*Message_Assistant)
	return ok
}

func (x *Message) HasTool() bool {
	if x == nil {
		return false
	}
	_, ok := x.Message.(*Message_Tool)
	return ok
}

func (x *Message) ClearCreateTime() {
	x.CreateTime = nil
}

func (x *Message) ClearMessage() {
	x.Message = nil
}

func (x *Message) ClearSystem() {
	if _, ok := x.Message.(*Message_System); ok {
		x.Message = nil
	}
}

func (x *Message) ClearUser() {
	if _, ok := x.Message.(*Message_User); ok {
		x.Message = nil
	}
}

func (x *Message) ClearAssistant() {
	if _, ok := x.Message.(*Message_Assistant); ok {
		x.Message = nil
	}
}

func (x *Message) ClearTool() {
	if _, ok := x.Message.(*Message_Tool); ok {
		x.Message = nil
	}
}

const Message_Message_not_set_case case_Message_Message = 0
const Message_System_case case_Message_Message = 10
const Message_User_case case_Message_Message = 11
const Message_Assistant_case case_Message_Message = 12
const Message_Tool_case case_Message_Message = 13

func (x *Message) WhichMessage() case_Message_Message {
	if x == nil {
		return Message_Message_not_set_case
	}
	switch x.Message.(type) {
	case *Message_System:
		return Message_System_case
	case *Message_User:
		return Message_User_case
	case *Message_Assistant:
		return Message_Assistant_case
	case *Message_Tool:
		return Message_Tool_case
	default:
		return Message_Message_not_set_case
	}
}

type Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// When this message was created.
	CreateTime *timestamppb.Timestamp
	// Arbitrary key-value metadata associated with the message.
	Metadata map[string]string
	// Role of the message sender.
	Role Role
	// The specific message type. Exactly one must be set.

	// Fields of oneof Message:
	// A system instruction message.
	System *SystemMessage
	// A user input message.
	User *UserMessage
	// An assistant response message.
	Assistant *AssistantMessage
	// A tool result message.
	Tool *ToolResultMessage
	// -- end of Message
}

func (b0 Message_builder) Build() *Message {
	m0 := &Message{}
	b, x := &b0, m0
	_, _ = b, x
	x.CreateTime = b.CreateTime
	x.Metadata = b.Metadata
	x.Role = b.Role
	if b.System != nil {
		x.Message = &Message_System{b.System}
	}
	if b.User != nil {
		x.Message = &Message_User{b.User}
	}
	if b.Assistant != nil {
		x.Message = &Message_Assistant{b.Assistant}
	}
	if b.Tool != nil {
		x.Message = &Message_Tool{b.Tool}
	}
	return m0
}

type case_Message_Message protoreflect.FieldNumber

func (x case_Message_Message) String() string {
	md := file_malonaz_ai_v1_message_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_System struct {
	// A system instruction message.
	System *SystemMessage `protobuf:"bytes,10,opt,name=system,proto3,oneof"`
}

type Message_User struct {
	// A user input message.
	User *UserMessage `protobuf:"bytes,11,opt,name=user,proto3,oneof"`
}

type Message_Assistant struct {
	// An assistant response message.
	Assistant *AssistantMessage `protobuf:"bytes,12,opt,name=assistant,proto3,oneof"`
}

type Message_Tool struct {
	// A tool result message.
	Tool *ToolResultMessage `protobuf:"bytes,13,opt,name=tool,proto3,oneof"`
}

func (*Message_System) isMessage_Message() {}

func (*Message_User) isMessage_Message() {}

func (*Message_Assistant) isMessage_Message() {}

func (*Message_Tool) isMessage_Message() {}

// System message that sets the behavior, context, and instructions for the AI.
// Typically placed at the beginning of a conversation to establish the AI's persona,
// constraints, and response style.
type SystemMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The instruction content for the AI system.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SystemMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemMessage) SetContent(v string) {
	x.Content = v
}

type SystemMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The instruction content for the AI system.
	Content string
}

func (b0 SystemMessage_builder) Build() *SystemMessage {
	m0 := &SystemMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Content = b.Content
	return m0
}

// Assistant message representing a response from the AI model.
// Must contain either text content, tool calls, or both.
type AssistantMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Internal reasoning or chain-of-thought generated by the model.
	// Only populated when using models that support extended thinking.
	Reasoning string `protobuf:"bytes,1,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// The text content of the assistant's response.
	// May be empty if the assistant is only making tool calls.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Structured content extracted from the response when TextToTextConfiguration.extract_json_object is true.
	StructuredContent *structpb.Struct `protobuf:"bytes,3,opt,name=structured_content,json=structuredContent,proto3" json:"structured_content,omitempty"`
	// Tool invocations requested by the assistant.
	// When present, the caller should execute these tools and return results
	// via ToolMessage before continuing the conversation.
	ToolCalls []*ToolCall `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// Generated images.
	Images        []*Image `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantMessage) Reset() {
	*x = AssistantMessage{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantMessage) ProtoMessage() {}

func (x *AssistantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssistantMessage) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *AssistantMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AssistantMessage) GetStructuredContent() *structpb.Struct {
	if x != nil {
		return x.StructuredContent
	}
	return nil
}

func (x *AssistantMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *AssistantMessage) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AssistantMessage) SetReasoning(v string) {
	x.Reasoning = v
}

func (x *AssistantMessage) SetContent(v string) {
	x.Content = v
}

func (x *AssistantMessage) SetStructuredContent(v *structpb.Struct) {
	x.StructuredContent = v
}

func (x *AssistantMessage) SetToolCalls(v []*ToolCall) {
	x.ToolCalls = v
}

func (x *AssistantMessage) SetImages(v []*Image) {
	x.Images = v
}

func (x *AssistantMessage) HasStructuredContent() bool {
	if x == nil {
		return false
	}
	return x.StructuredContent != nil
}

func (x *AssistantMessage) ClearStructuredContent() {
	x.StructuredContent = nil
}

type AssistantMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Internal reasoning or chain-of-thought generated by the model.
	// Only populated when using models that support extended thinking.
	Reasoning string
	// The text content of the assistant's response.
	// May be empty if the assistant is only making tool calls.
	Content string
	// Structured content extracted from the response when TextToTextConfiguration.extract_json_object is true.
	StructuredContent *structpb.Struct
	// Tool invocations requested by the assistant.
	// When present, the caller should execute these tools and return results
	// via ToolMessage before continuing the conversation.
	ToolCalls []*ToolCall
	// Generated images.
	Images []*Image
}

func (b0 AssistantMessage_builder) Build() *AssistantMessage {
	m0 := &AssistantMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Reasoning = b.Reasoning
	x.Content = b.Content
	x.StructuredContent = b.StructuredContent
	x.ToolCalls = b.ToolCalls
	x.Images = b.Images
	return m0
}

// Result of a tool invocation.
// Sent in response to an AssistantMessage that requested tool calls.
type ToolResultMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The unique identifier of the tool call this result responds to.
	// Must match the id field from a ToolCall in a preceding AssistantMessage.
	ToolCallId string `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// The name of the tool that created this result.
	ToolName string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// The result of a tool execution.
	Result        *ToolResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultMessage) Reset() {
	*x = ToolResultMessage{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultMessage) ProtoMessage() {}

func (x *ToolResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolResultMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultMessage) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResultMessage) GetResult() *ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolResultMessage) SetToolCallId(v string) {
	x.ToolCallId = v
}

func (x *ToolResultMessage) SetToolName(v string) {
	x.ToolName = v
}

func (x *ToolResultMessage) SetResult(v *ToolResult) {
	x.Result = v
}

func (x *ToolResultMessage) HasResult() bool {
	if x == nil {
		return false
	}
	return x.Result != nil
}

func (x *ToolResultMessage) ClearResult() {
	x.Result = nil
}

type ToolResultMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The unique identifier of the tool call this result responds to.
	// Must match the id field from a ToolCall in a preceding AssistantMessage.
	ToolCallId string
	// The name of the tool that created this result.
	ToolName string
	// The result of a tool execution.
	Result *ToolResult
}

func (b0 ToolResultMessage_builder) Build() *ToolResultMessage {
	m0 := &ToolResultMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.ToolCallId = b.ToolCallId
	x.ToolName = b.ToolName
	x.Result = b.Result
	return m0
}

// User message representing input from a human participant in the conversation.
type UserMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The content blocks of the user's input.
	// Supports mixed content types (text, images) in a single message.
	ContentBlocks []*ContentBlock `protobuf:"bytes,1,rep,name=content_blocks,json=contentBlocks,proto3" json:"content_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserMessage) GetContentBlocks() []*ContentBlock {
	if x != nil {
		return x.ContentBlocks
	}
	return nil
}

func (x *UserMessage) SetContentBlocks(v []*ContentBlock) {
	x.ContentBlocks = v
}

type UserMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The content blocks of the user's input.
	// Supports mixed content types (text, images) in a single message.
	ContentBlocks []*ContentBlock
}

func (b0 UserMessage_builder) Build() *UserMessage {
	m0 := &UserMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.ContentBlocks = b.ContentBlocks
	return m0
}

// A block of content within a message.
type ContentBlock struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The content type.
	//
	// Types that are valid to be assigned to Content:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	Content       isContentBlock_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContentBlock) GetContent() isContentBlock_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ContentBlock) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContentBlock) GetImage() *Image {
	if x != nil {
		if x, ok := x.Content.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ContentBlock) SetText(v string) {
	x.Content = &ContentBlock_Text{v}
}

func (x *ContentBlock) SetImage(v *Image) {
	if v == nil {
		x.Content = nil
		return
	}
	x.Content = &ContentBlock_Image{v}
}

func (x *ContentBlock) HasContent() bool {
	if x == nil {
		return false
	}
	return x.Content != nil
}

func (x *ContentBlock) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.Content.(*ContentBlock_Text)
	return ok
}

func (x *ContentBlock) HasImage() bool {
	if x == nil {
		return false
	}
	_, ok := x.Content.(*ContentBlock_Image)
	return ok
}

func (x *ContentBlock) ClearContent() {
	x.Content = nil
}

func (x *ContentBlock) ClearText() {
	if _, ok := x.Content.(*ContentBlock_Text); ok {
		x.Content = nil
	}
}

func (x *ContentBlock) ClearImage() {
	if _, ok := x.Content.(*ContentBlock_Image); ok {
		x.Content = nil
	}
}

const ContentBlock_Content_not_set_case case_ContentBlock_Content = 0
const ContentBlock_Text_case case_ContentBlock_Content = 1
const ContentBlock_Image_case case_ContentBlock_Content = 2

func (x *ContentBlock) WhichContent() case_ContentBlock_Content {
	if x == nil {
		return ContentBlock_Content_not_set_case
	}
	switch x.Content.(type) {
	case *ContentBlock_Text:
		return ContentBlock_Text_case
	case *ContentBlock_Image:
		return ContentBlock_Image_case
	default:
		return ContentBlock_Content_not_set_case
	}
}

type ContentBlock_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The content type.

	// Fields of oneof Content:
	// Text content.
	Text *string
	// Image content.
	Image *Image
	// -- end of Content
}

func (b0 ContentBlock_builder) Build() *ContentBlock {
	m0 := &ContentBlock{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		x.Content = &ContentBlock_Text{*b.Text}
	}
	if b.Image != nil {
		x.Content = &ContentBlock_Image{b.Image}
	}
	return m0
}

type case_ContentBlock_Content protoreflect.FieldNumber

func (x case_ContentBlock_Content) String() string {
	md := file_malonaz_ai_v1_message_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isContentBlock_Content interface {
	isContentBlock_Content()
}

type ContentBlock_Text struct {
	// Text content.
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	// Image content.
	Image *Image `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Content() {}

func (*ContentBlock_Image) isContentBlock_Content() {}

// An image block.
type Image struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The image source.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*Image_Data
	//	*Image_Url
	Source isImage_Source `protobuf_oneof:"source"`
	// MIME type of the image (e.g., "image/png", "image/jpeg", "image/webp", "image/gif").
	// Required when using `data`, optional when using `url`.
	MediaType string `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Quality of the image.
	Quality       ImageQuality `protobuf:"varint,4,opt,name=quality,proto3,enum=malonaz.ai.v1.ImageQuality" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_ai_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Image) GetSource() isImage_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Image) GetData() []byte {
	if x != nil {
		if x, ok := x.Source.(*Image_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Image) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*Image_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *Image) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Image) GetQuality() ImageQuality {
	if x != nil {
		return x.Quality
	}
	return ImageQuality_IMAGE_QUALITY_UNSPECIFIED
}

func (x *Image) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.Source = &Image_Data{v}
}

func (x *Image) SetUrl(v string) {
	x.Source = &Image_Url{v}
}

func (x *Image) SetMediaType(v string) {
	x.MediaType = v
}

func (x *Image) SetQuality(v ImageQuality) {
	x.Quality = v
}

func (x *Image) HasSource() bool {
	if x == nil {
		return false
	}
	return x.Source != nil
}

func (x *Image) HasData() bool {
	if x == nil {
		return false
	}
	_, ok := x.Source.(*Image_Data)
	return ok
}

func (x *Image) HasUrl() bool {
	if x == nil {
		return false
	}
	_, ok := x.Source.(*Image_Url)
	return ok
}

func (x *Image) ClearSource() {
	x.Source = nil
}

func (x *Image) ClearData() {
	if _, ok := x.Source.(*Image_Data); ok {
		x.Source = nil
	}
}

func (x *Image) ClearUrl() {
	if _, ok := x.Source.(*Image_Url); ok {
		x.Source = nil
	}
}

const Image_Source_not_set_case case_Image_Source = 0
const Image_Data_case case_Image_Source = 1
const Image_Url_case case_Image_Source = 2

func (x *Image) WhichSource() case_Image_Source {
	if x == nil {
		return Image_Source_not_set_case
	}
	switch x.Source.(type) {
	case *Image_Data:
		return Image_Data_case
	case *Image_Url:
		return Image_Url_case
	default:
		return Image_Source_not_set_case
	}
}

type Image_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The image source.

	// Fields of oneof Source:
	// Raw image bytes.
	Data []byte
	// URL to the image. Supports both HTTPS URLs and data URLs
	// (e.g., "data:image/png;base64,...").
	Url *string
	// -- end of Source
	// MIME type of the image (e.g., "image/png", "image/jpeg", "image/webp", "image/gif").
	// Required when using `data`, optional when using `url`.
	MediaType string
	// Quality of the image.
	Quality ImageQuality
}

func (b0 Image_builder) Build() *Image {
	m0 := &Image{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		x.Source = &Image_Data{b.Data}
	}
	if b.Url != nil {
		x.Source = &Image_Url{*b.Url}
	}
	x.MediaType = b.MediaType
	x.Quality = b.Quality
	return m0
}

type case_Image_Source protoreflect.FieldNumber

func (x case_Image_Source) String() string {
	md := file_malonaz_ai_v1_message_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isImage_Source interface {
	isImage_Source()
}

type Image_Data struct {
	// Raw image bytes.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type Image_Url struct {
	// URL to the image. Supports both HTTPS URLs and data URLs
	// (e.g., "data:image/png;base64,...").
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*Image_Data) isImage_Source() {}

func (*Image_Url) isImage_Source() {}

var File_malonaz_ai_v1_message_proto protoreflect.FileDescriptor

const file_malonaz_ai_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1bmalonaz/ai/v1/message.proto\x12\rmalonaz.ai.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18malonaz/ai/v1/tool.proto\"\xd0\x05\n" +
	"\aMessage\x12;\n" +
	"\vcreate_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.malonaz.ai.v1.Message.MetadataEntryR\bmetadata\x123\n" +
	"\x04role\x18\x03 \x01(\x0e2\x13.malonaz.ai.v1.RoleB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04role\x126\n" +
	"\x06system\x18\n" +
	" \x01(\v2\x1c.malonaz.ai.v1.SystemMessageH\x00R\x06system\x120\n" +
	"\x04user\x18\v \x01(\v2\x1a.malonaz.ai.v1.UserMessageH\x00R\x04user\x12?\n" +
	"\tassistant\x18\f \x01(\v2\x1f.malonaz.ai.v1.AssistantMessageH\x00R\tassistant\x126\n" +
	"\x04tool\x18\r \x01(\v2 .malonaz.ai.v1.ToolResultMessageH\x00R\x04tool\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xde\x01\xbaH\xda\x01\x1a\xd7\x01\n" +
	"\x19role_matches_message_type\x12\x1crole must match message type\x1a\x9b\x01(this.role == 1 && has(this.system)) || (this.role == 2 && has(this.assistant)) || (this.role == 3 && has(this.user)) || (this.role == 4 && has(this.tool))B\x10\n" +
	"\amessage\x12\x05\xbaH\x02\b\x01\"1\n" +
	"\rSystemMessage\x12 \n" +
	"\acontent\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\acontent\"\xf6\x03\n" +
	"\x10AssistantMessage\x12\x1c\n" +
	"\treasoning\x18\x01 \x01(\tR\treasoning\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12F\n" +
	"\x12structured_content\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x11structuredContent\x126\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x17.malonaz.ai.v1.ToolCallR\ttoolCalls\x12,\n" +
	"\x06images\x18\x05 \x03(\v2\x14.malonaz.ai.v1.ImageR\x06images:\xfb\x01\xbaH\xf7\x01\x1a\xf4\x01\n" +
	"(assistant_requires_content_or_tool_calls\x12^AssistantMessage must have either content, structured_content, tool_calls, or generated_images\x1ahthis.content != '' || has(this.structured_content) || size(this.tool_calls) > 0 || size(this.images) > 0\"\x95\x01\n" +
	"\x11ToolResultMessage\x12(\n" +
	"\ftool_call_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"toolCallId\x12#\n" +
	"\ttool_name\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btoolName\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x19.malonaz.ai.v1.ToolResultR\x06result\"[\n" +
	"\vUserMessage\x12L\n" +
	"\x0econtent_blocks\x18\x01 \x03(\v2\x1b.malonaz.ai.v1.ContentBlockB\b\xbaH\x05\x92\x01\x02\b\x01R\rcontentBlocks\"d\n" +
	"\fContentBlock\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12,\n" +
	"\x05image\x18\x02 \x01(\v2\x14.malonaz.ai.v1.ImageH\x00R\x05imageB\x10\n" +
	"\acontent\x12\x05\xbaH\x02\b\x01\"\x9f\x02\n" +
	"\x05Image\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12?\n" +
	"\aquality\x18\x04 \x01(\x0e2\x1b.malonaz.ai.v1.ImageQualityB\b\xbaH\x05\x82\x01\x02\x10\x01R\aquality:{\xbaHx\x1av\n" +
	"\"image_requires_media_type_for_data\x12&media_type is required when using data\x1a(!has(this.data) || this.media_type != ''B\x0f\n" +
	"\x06source\x12\x05\xbaH\x02\b\x01*\xa3\x01\n" +
	"\x0fReasoningEffort\x12 \n" +
	"\x1cREASONING_EFFORT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REASONING_EFFORT_DEFAULT\x10\x01\x12\x18\n" +
	"\x14REASONING_EFFORT_LOW\x10\x02\x12\x1b\n" +
	"\x17REASONING_EFFORT_MEDIUM\x10\x03\x12\x19\n" +
	"\x15REASONING_EFFORT_HIGH\x10\x04*_\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x01\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x02\x12\r\n" +
	"\tROLE_USER\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x04*t\n" +
	"\fImageQuality\x12\x1d\n" +
	"\x19IMAGE_QUALITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12IMAGE_QUALITY_AUTO\x10\x01\x12\x15\n" +
	"\x11IMAGE_QUALITY_LOW\x10\x02\x12\x16\n" +
	"\x12IMAGE_QUALITY_HIGH\x10\x03B(Z&github.com/malonaz/core/genproto/ai/v1b\x06proto3"

var file_malonaz_ai_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_malonaz_ai_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_malonaz_ai_v1_message_proto_goTypes = []any{
	(ReasoningEffort)(0),          // 0: malonaz.ai.v1.ReasoningEffort
	(Role)(0),                     // 1: malonaz.ai.v1.Role
	(ImageQuality)(0),             // 2: malonaz.ai.v1.ImageQuality
	(*Message)(nil),               // 3: malonaz.ai.v1.Message
	(*SystemMessage)(nil),         // 4: malonaz.ai.v1.SystemMessage
	(*AssistantMessage)(nil),      // 5: malonaz.ai.v1.AssistantMessage
	(*ToolResultMessage)(nil),     // 6: malonaz.ai.v1.ToolResultMessage
	(*UserMessage)(nil),           // 7: malonaz.ai.v1.UserMessage
	(*ContentBlock)(nil),          // 8: malonaz.ai.v1.ContentBlock
	(*Image)(nil),                 // 9: malonaz.ai.v1.Image
	nil,                           // 10: malonaz.ai.v1.Message.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
	(*ToolCall)(nil),              // 13: malonaz.ai.v1.ToolCall
	(*ToolResult)(nil),            // 14: malonaz.ai.v1.ToolResult
}
var file_malonaz_ai_v1_message_proto_depIdxs = []int32{
	11, // 0: malonaz.ai.v1.Message.create_time:type_name -> google.protobuf.Timestamp
	10, // 1: malonaz.ai.v1.Message.metadata:type_name -> malonaz.ai.v1.Message.MetadataEntry
	1,  // 2: malonaz.ai.v1.Message.role:type_name -> malonaz.ai.v1.Role
	4,  // 3: malonaz.ai.v1.Message.system:type_name -> malonaz.ai.v1.SystemMessage
	7,  // 4: malonaz.ai.v1.Message.user:type_name -> malonaz.ai.v1.UserMessage
	5,  // 5: malonaz.ai.v1.Message.assistant:type_name -> malonaz.ai.v1.AssistantMessage
	6,  // 6: malonaz.ai.v1.Message.tool:type_name -> malonaz.ai.v1.ToolResultMessage
	12, // 7: malonaz.ai.v1.AssistantMessage.structured_content:type_name -> google.protobuf.Struct
	13, // 8: malonaz.ai.v1.AssistantMessage.tool_calls:type_name -> malonaz.ai.v1.ToolCall
	9,  // 9: malonaz.ai.v1.AssistantMessage.images:type_name -> malonaz.ai.v1.Image
	14, // 10: malonaz.ai.v1.ToolResultMessage.result:type_name -> malonaz.ai.v1.ToolResult
	8,  // 11: malonaz.ai.v1.UserMessage.content_blocks:type_name -> malonaz.ai.v1.ContentBlock
	9,  // 12: malonaz.ai.v1.ContentBlock.image:type_name -> malonaz.ai.v1.Image
	2,  // 13: malonaz.ai.v1.Image.quality:type_name -> malonaz.ai.v1.ImageQuality
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_malonaz_ai_v1_message_proto_init() }
func file_malonaz_ai_v1_message_proto_init() {
	if File_malonaz_ai_v1_message_proto != nil {
		return
	}
	file_malonaz_ai_v1_tool_proto_init()
	file_malonaz_ai_v1_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_System)(nil),
		(*Message_User)(nil),
		(*Message_Assistant)(nil),
		(*Message_Tool)(nil),
	}
	file_malonaz_ai_v1_message_proto_msgTypes[5].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
	}
	file_malonaz_ai_v1_message_proto_msgTypes[6].OneofWrappers = []any{
		(*Image_Data)(nil),
		(*Image_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malonaz_ai_v1_message_proto_rawDesc), len(file_malonaz_ai_v1_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_malonaz_ai_v1_message_proto_goTypes,
		DependencyIndexes: file_malonaz_ai_v1_message_proto_depIdxs,
		EnumInfos:         file_malonaz_ai_v1_message_proto_enumTypes,
		MessageInfos:      file_malonaz_ai_v1_message_proto_msgTypes,
	}.Build()
	File_malonaz_ai_v1_message_proto = out.File
	file_malonaz_ai_v1_message_proto_goTypes = nil
	file_malonaz_ai_v1_message_proto_depIdxs = nil
}
