# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: malonaz/ai/v1/voice.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'malonaz/ai/v1/voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19malonaz/ai/v1/voice.proto\x12\rmalonaz.ai.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x19google/api/resource.proto\"\xc4\x02\n\x05Voice\x12\x1b\n\x04name\x18\x01 \x01(\tB\r\xbaH\nr\x05\x10\x01\x18\x80\x01\xc8\x01\x01\x12#\n\x0c\x64isplay_name\x18\x02 \x01(\tB\r\xbaH\nr\x05\x10\x01\x18\x80\x01\xc8\x01\x01\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tB\x0b\xbaH\x08r\x03\x18\xf4\x03\xc8\x01\x01\x12\x36\n\x06gender\x18\x04 \x01(\x0e\x32\x1a.malonaz.ai.v1.VoiceGenderB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00\x12#\n\x0bpreview_url\x18\x05 \x01(\tB\x0e\xbaH\x0br\x06\x18\x80\x10\x88\x01\x01\xd8\x01\x01\x12@\n\rmodel_configs\x18\x06 \x03(\x0b\x32\x1f.malonaz.ai.v1.VoiceModelConfigB\x08\xbaH\x05\x92\x01\x02\x08\x01:8\xea\x41\x35\n\x14\x61i.malonaz.com/Voice\x12\x0evoices/{voice}*\x06voices2\x05voice\"s\n\x10VoiceModelConfig\x12\x35\n\x05model\x18\x01 \x01(\tB&\xfa\x41\x16\n\x14\x61i.malonaz.com/Model\xbaH\nr\x05\x10\x01\x18\x80\x01\xc8\x01\x01\x12(\n\x11provider_voice_id\x18\x02 \x01(\tB\r\xbaH\nr\x05\x10\x01\x18\x80\x01\xc8\x01\x01*[\n\x0bVoiceGender\x12\x1c\n\x18VOICE_GENDER_UNSPECIFIED\x10\x00\x12\x15\n\x11VOICE_GENDER_MALE\x10\x01\x12\x17\n\x13VOICE_GENDER_FEMALE\x10\x02\x42(Z&github.com/malonaz/core/genproto/ai/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'malonaz.ai.v1.voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/malonaz/core/genproto/ai/v1'
  _globals['_VOICE'].fields_by_name['name']._loaded_options = None
  _globals['_VOICE'].fields_by_name['name']._serialized_options = b'\272H\nr\005\020\001\030\200\001\310\001\001'
  _globals['_VOICE'].fields_by_name['display_name']._loaded_options = None
  _globals['_VOICE'].fields_by_name['display_name']._serialized_options = b'\272H\nr\005\020\001\030\200\001\310\001\001'
  _globals['_VOICE'].fields_by_name['description']._loaded_options = None
  _globals['_VOICE'].fields_by_name['description']._serialized_options = b'\272H\010r\003\030\364\003\310\001\001'
  _globals['_VOICE'].fields_by_name['gender']._loaded_options = None
  _globals['_VOICE'].fields_by_name['gender']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_VOICE'].fields_by_name['preview_url']._loaded_options = None
  _globals['_VOICE'].fields_by_name['preview_url']._serialized_options = b'\272H\013r\006\030\200\020\210\001\001\330\001\001'
  _globals['_VOICE'].fields_by_name['model_configs']._loaded_options = None
  _globals['_VOICE'].fields_by_name['model_configs']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_VOICE']._loaded_options = None
  _globals['_VOICE']._serialized_options = b'\352A5\n\024ai.malonaz.com/Voice\022\016voices/{voice}*\006voices2\005voice'
  _globals['_VOICEMODELCONFIG'].fields_by_name['model']._loaded_options = None
  _globals['_VOICEMODELCONFIG'].fields_by_name['model']._serialized_options = b'\372A\026\n\024ai.malonaz.com/Model\272H\nr\005\020\001\030\200\001\310\001\001'
  _globals['_VOICEMODELCONFIG'].fields_by_name['provider_voice_id']._loaded_options = None
  _globals['_VOICEMODELCONFIG'].fields_by_name['provider_voice_id']._serialized_options = b'\272H\nr\005\020\001\030\200\001\310\001\001'
  _globals['_VOICEGENDER']._serialized_start=544
  _globals['_VOICEGENDER']._serialized_end=635
  _globals['_VOICE']._serialized_start=101
  _globals['_VOICE']._serialized_end=425
  _globals['_VOICEMODELCONFIG']._serialized_start=427
  _globals['_VOICEMODELCONFIG']._serialized_end=542
# @@protoc_insertion_point(module_scope)
