package(default_visibility = ["PUBLIC"])

export_file(
    name = "utils.go.tmpl",
    src = "utils.go.tmpl",
)

############# SERVICE #################
export_file(
    name = "main.go.tmpl",
    src = "main.go.tmpl",
)

export_file(
    name = "main.opts.go.tmpl",
    src = "main.opts.go.tmpl",
)

export_file(
    name = "service.go.tmpl",
    src = "service.go.tmpl",
)

export_file(
    name = "k8s.yaml.tmpl",
    src = "k8s.yaml.tmpl",
)

############## SCHEMAS ###################
export_file(
    name = "service_manifest.schema",
    src = "service_manifest.schema",
)

export_file(
    name = "service.go.schema",
    src = "service.go.schema",
)
