go_library(
    name = "websocket",
    srcs = [
        "client.go",
        "handler.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:github.com__go-json-experiment__json",
        "//third_party/go:github.com__gorilla__websocket",
    ],
)
