go_library(
    name = "websocket",
    srcs = [
        "server.go",
        "websocket.go",
    ],
    visibility = ["//..."],
    deps = [
        "//go/logging",
        "//third_party/go:github.com__gorilla__websocket",
        "//third_party/go:github.com__pkg__errors",
    ],
)
