// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: malonaz/codegen/nats/v1/nats.proto

//go:build !protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/malonaz/core/genproto/nats/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options controlling which NATS events are generated for a resource.
// Each field corresponds to a standard AIP method. When set, the code
// generator produces a typed event message and publishes it on the
// resource's NATS subject after the method completes successfully.
type EventOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Sets the stream on which events will be published.
	// If omitted, the FQN of the message this annotation is attached to will be used.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// Options for the created event, published when a resource is created via its Create method.
	// Produces a <Resource>CreatedEvent containing the newly created resource.
	// If unset, no created event is generated.
	Created []*EventMethodOptions `protobuf:"bytes,2,rep,name=created,proto3" json:"created,omitempty"`
	// Options for the updated event, published when a resource is updated via its Update method.
	// Produces a <Resource>UpdatedEvent containing the previous state, the new
	// state, and the field mask that was applied.
	// If unset, no updated event is generated.
	Updated []*EventMethodOptions `protobuf:"bytes,3,rep,name=updated,proto3" json:"updated,omitempty"`
	// Options for the deleted event, published when a resource is deleted via its Delete method.
	// Produces a <Resource>DeletedEvent containing the resource at deletion time.
	// If unset, no deleted event is generated.
	Deleted       []*EventMethodOptions `protobuf:"bytes,4,rep,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_malonaz_codegen_nats_v1_nats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_codegen_nats_v1_nats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventOptions) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *EventOptions) GetCreated() []*EventMethodOptions {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *EventOptions) GetUpdated() []*EventMethodOptions {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *EventOptions) GetDeleted() []*EventMethodOptions {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *EventOptions) SetStream(v string) {
	x.Stream = v
}

func (x *EventOptions) SetCreated(v []*EventMethodOptions) {
	x.Created = v
}

func (x *EventOptions) SetUpdated(v []*EventMethodOptions) {
	x.Updated = v
}

func (x *EventOptions) SetDeleted(v []*EventMethodOptions) {
	x.Deleted = v
}

type EventOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Sets the stream on which events will be published.
	// If omitted, the FQN of the message this annotation is attached to will be used.
	Stream string
	// Options for the created event, published when a resource is created via its Create method.
	// Produces a <Resource>CreatedEvent containing the newly created resource.
	// If unset, no created event is generated.
	Created []*EventMethodOptions
	// Options for the updated event, published when a resource is updated via its Update method.
	// Produces a <Resource>UpdatedEvent containing the previous state, the new
	// state, and the field mask that was applied.
	// If unset, no updated event is generated.
	Updated []*EventMethodOptions
	// Options for the deleted event, published when a resource is deleted via its Delete method.
	// Produces a <Resource>DeletedEvent containing the resource at deletion time.
	// If unset, no deleted event is generated.
	Deleted []*EventMethodOptions
}

func (b0 EventOptions_builder) Build() *EventOptions {
	m0 := &EventOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Stream = b.Stream
	x.Created = b.Created
	x.Updated = b.Updated
	x.Deleted = b.Deleted
	return m0
}

// Options controlling subject routing and conditional publishing for a single event type.
type EventMethodOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The subject of this event.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Fields to inject as subject tokens, appended in order after the event type.
	// For example, specifying ["provider_id"] produces subjects like
	// `<stream>.<subject>.<provider_id_value>`.
	// Multiple fields are appended in order: `<stream>.<subject>.<field1_value>.<field2_value>`.
	//
	// Each referenced field must have a non-empty strirng representation
	// as its value must always be present.
	//
	// String fields are used as-is.
	// Enum fields have their type prefix stripped and the remainder is lower_cased
	// (e.g. PROVIDER_TYPE_AWS -> aws).
	SubjectFields []string `protobuf:"bytes,2,rep,name=subject_fields,json=subjectFields,proto3" json:"subject_fields,omitempty"`
	// Optional CEL expression evaluated against the resource event message.
	// If present, the event is only published when the expression evaluates to true.
	// The expression has access to:
	//
	//	`this.resource` => on `created`, `updated` & `deleted` events.
	//	`this.previous_resource` => on `updated` events.
	//	`this.update_mask` => on `updated` events.
	//
	// Example: "this.resource.status == 'ACTIVE' && this.resource.provider_id != ”"
	Cel           string `protobuf:"bytes,3,opt,name=cel,proto3" json:"cel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMethodOptions) Reset() {
	*x = EventMethodOptions{}
	mi := &file_malonaz_codegen_nats_v1_nats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMethodOptions) ProtoMessage() {}

func (x *EventMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_malonaz_codegen_nats_v1_nats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventMethodOptions) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EventMethodOptions) GetSubjectFields() []string {
	if x != nil {
		return x.SubjectFields
	}
	return nil
}

func (x *EventMethodOptions) GetCel() string {
	if x != nil {
		return x.Cel
	}
	return ""
}

func (x *EventMethodOptions) SetSubject(v string) {
	x.Subject = v
}

func (x *EventMethodOptions) SetSubjectFields(v []string) {
	x.SubjectFields = v
}

func (x *EventMethodOptions) SetCel(v string) {
	x.Cel = v
}

type EventMethodOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The subject of this event.
	Subject string
	// Fields to inject as subject tokens, appended in order after the event type.
	// For example, specifying ["provider_id"] produces subjects like
	// `<stream>.<subject>.<provider_id_value>`.
	// Multiple fields are appended in order: `<stream>.<subject>.<field1_value>.<field2_value>`.
	//
	// Each referenced field must have a non-empty strirng representation
	// as its value must always be present.
	//
	// String fields are used as-is.
	// Enum fields have their type prefix stripped and the remainder is lower_cased
	// (e.g. PROVIDER_TYPE_AWS -> aws).
	SubjectFields []string
	// Optional CEL expression evaluated against the resource event message.
	// If present, the event is only published when the expression evaluates to true.
	// The expression has access to:
	//
	//	`this.resource` => on `created`, `updated` & `deleted` events.
	//	`this.previous_resource` => on `updated` events.
	//	`this.update_mask` => on `updated` events.
	//
	// Example: "this.resource.status == 'ACTIVE' && this.resource.provider_id != ”"
	Cel string
}

func (b0 EventMethodOptions_builder) Build() *EventMethodOptions {
	m0 := &EventMethodOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Subject = b.Subject
	x.SubjectFields = b.SubjectFields
	x.Cel = b.Cel
	return m0
}

var file_malonaz_codegen_nats_v1_nats_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: ([]*v1.StreamOptions)(nil),
		Field:         74000,
		Name:          "malonaz.codegen.nats.v1.stream",
		Tag:           "bytes,74000,rep,name=stream",
		Filename:      "malonaz/codegen/nats/v1/nats.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         74001,
		Name:          "malonaz.codegen.nats.v1.event",
		Tag:           "bytes,74001,opt,name=event",
		Filename:      "malonaz/codegen/nats/v1/nats.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Stream options for resources in this service.
	//
	// repeated malonaz.nats.v1.StreamOptions stream = 74000;
	E_Stream = &file_malonaz_codegen_nats_v1_nats_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Event generation options for this resource.
	//
	// optional malonaz.codegen.nats.v1.EventOptions event = 74001;
	E_Event = &file_malonaz_codegen_nats_v1_nats_proto_extTypes[1]
)

var File_malonaz_codegen_nats_v1_nats_proto protoreflect.FileDescriptor

const file_malonaz_codegen_nats_v1_nats_proto_rawDesc = "" +
	"\n" +
	"\"malonaz/codegen/nats/v1/nats.proto\x12\x17malonaz.codegen.nats.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/descriptor.proto\x1a\x1cmalonaz/nats/v1/stream.proto\"\x83\x02\n" +
	"\fEventOptions\x12\x1e\n" +
	"\x06stream\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06stream\x12E\n" +
	"\acreated\x18\x02 \x03(\v2+.malonaz.codegen.nats.v1.EventMethodOptionsR\acreated\x12E\n" +
	"\aupdated\x18\x03 \x03(\v2+.malonaz.codegen.nats.v1.EventMethodOptionsR\aupdated\x12E\n" +
	"\adeleted\x18\x04 \x03(\v2+.malonaz.codegen.nats.v1.EventMethodOptionsR\adeleted\"o\n" +
	"\x12EventMethodOptions\x12 \n" +
	"\asubject\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\asubject\x12%\n" +
	"\x0esubject_fields\x18\x02 \x03(\tR\rsubjectFields\x12\x10\n" +
	"\x03cel\x18\x03 \x01(\tR\x03cel:Y\n" +
	"\x06stream\x12\x1f.google.protobuf.ServiceOptions\x18\x90\xc2\x04 \x03(\v2\x1e.malonaz.nats.v1.StreamOptionsR\x06stream:^\n" +
	"\x05event\x12\x1f.google.protobuf.MessageOptions\x18\x91\xc2\x04 \x01(\v2%.malonaz.codegen.nats.v1.EventOptionsR\x05eventB2Z0github.com/malonaz/core/genproto/codegen/nats/v1b\x06proto3"

var file_malonaz_codegen_nats_v1_nats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_malonaz_codegen_nats_v1_nats_proto_goTypes = []any{
	(*EventOptions)(nil),                // 0: malonaz.codegen.nats.v1.EventOptions
	(*EventMethodOptions)(nil),          // 1: malonaz.codegen.nats.v1.EventMethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*v1.StreamOptions)(nil),            // 4: malonaz.nats.v1.StreamOptions
}
var file_malonaz_codegen_nats_v1_nats_proto_depIdxs = []int32{
	1, // 0: malonaz.codegen.nats.v1.EventOptions.created:type_name -> malonaz.codegen.nats.v1.EventMethodOptions
	1, // 1: malonaz.codegen.nats.v1.EventOptions.updated:type_name -> malonaz.codegen.nats.v1.EventMethodOptions
	1, // 2: malonaz.codegen.nats.v1.EventOptions.deleted:type_name -> malonaz.codegen.nats.v1.EventMethodOptions
	2, // 3: malonaz.codegen.nats.v1.stream:extendee -> google.protobuf.ServiceOptions
	3, // 4: malonaz.codegen.nats.v1.event:extendee -> google.protobuf.MessageOptions
	4, // 5: malonaz.codegen.nats.v1.stream:type_name -> malonaz.nats.v1.StreamOptions
	0, // 6: malonaz.codegen.nats.v1.event:type_name -> malonaz.codegen.nats.v1.EventOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	5, // [5:7] is the sub-list for extension type_name
	3, // [3:5] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_malonaz_codegen_nats_v1_nats_proto_init() }
func file_malonaz_codegen_nats_v1_nats_proto_init() {
	if File_malonaz_codegen_nats_v1_nats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malonaz_codegen_nats_v1_nats_proto_rawDesc), len(file_malonaz_codegen_nats_v1_nats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_malonaz_codegen_nats_v1_nats_proto_goTypes,
		DependencyIndexes: file_malonaz_codegen_nats_v1_nats_proto_depIdxs,
		MessageInfos:      file_malonaz_codegen_nats_v1_nats_proto_msgTypes,
		ExtensionInfos:    file_malonaz_codegen_nats_v1_nats_proto_extTypes,
	}.Build()
	File_malonaz_codegen_nats_v1_nats_proto = out.File
	file_malonaz_codegen_nats_v1_nats_proto_goTypes = nil
	file_malonaz_codegen_nats_v1_nats_proto_depIdxs = nil
}
