go_library(
    name = "nats",
    srcs = ["nats.go"],
    visibility = ["//..."],
    deps = [
        "//go/pbutil",
        "//malonaz/codegen/nats/v1",
        "//third_party/go:github.com__huandu__xstrings",
        "//third_party/go:google.golang.org__protobuf__compiler__protogen",
    ],
)
